In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [3]:
from tensorflow.keras.layers import Dense

In [4]:
data=pd.read_csv("C:/Users/nchar/Desktop/english_to_french_translator/eng_-french.csv")
df=pd.DataFrame(data)
print(df.info())
df.dropna(axis=0,inplace=True)
inp=df["English words/sentences"][0:10000]
inp=list(inp)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175621 entries, 0 to 175620
Data columns (total 2 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   English words/sentences  175621 non-null  object
 1   French words/sentences   175621 non-null  object
dtypes: object(2)
memory usage: 2.7+ MB
None


In [5]:
inp=[(word.split()) for word in inp]

In [6]:
inp

[['Hi.'],
 ['Run!'],
 ['Run!'],
 ['Who?'],
 ['Wow!'],
 ['Fire!'],
 ['Help!'],
 ['Jump.'],
 ['Stop!'],
 ['Stop!'],
 ['Stop!'],
 ['Wait!'],
 ['Wait!'],
 ['Go', 'on.'],
 ['Go', 'on.'],
 ['Go', 'on.'],
 ['Hello!'],
 ['Hello!'],
 ['I', 'see.'],
 ['I', 'try.'],
 ['I', 'won!'],
 ['I', 'won!'],
 ['I', 'won.'],
 ['Oh', 'no!'],
 ['Attack!'],
 ['Attack!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Get', 'up.'],
 ['Go', 'now.'],
 ['Go', 'now.'],
 ['Go', 'now.'],
 ['Got', 'it!'],
 ['Got', 'it!'],
 ['Got', 'it?'],
 ['Got', 'it?'],
 ['Got', 'it?'],
 ['Hop', 'in.'],
 ['Hop', 'in.'],
 ['Hug', 'me.'],
 ['Hug', 'me.'],
 ['I', 'fell.'],
 ['I', 'fell.'],
 ['I', 'know.'],
 ['I', 'left.'],
 ['I', 'left.'],
 ['I', 'lied.'],
 ['I', 'lost.'],
 ['I', 'paid.'],
 ["I'm", '19.'],
 ["I'm", 'OK.'],
 ["I'm", 'OK.'],
 ['Listen.'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['Really?'],
 ['Real

In [7]:
t=tf.keras.preprocessing.text.Tokenizer()
t.fit_on_texts(inp)

In [25]:
inp_encds=t.texts_to_sequences(inp)
inp_encds

[[1262],
 [1263],
 [1263],
 [1264],
 [1946],
 [1265],
 [1947],
 [975],
 [976],
 [976],
 [976],
 [1266],
 [1266],
 [35, 202],
 [35, 202],
 [35, 202],
 [1267],
 [1267],
 [1, 450],
 [1, 190],
 [1, 792],
 [1, 792],
 [1, 154],
 [977, 1948],
 [1268],
 [1268],
 [793],
 [793],
 [793],
 [793],
 [33, 41],
 [35, 94],
 [35, 94],
 [35, 94],
 [46, 106],
 [46, 106],
 [46, 51],
 [46, 51],
 [46, 51],
 [1269, 100],
 [1269, 100],
 [978, 24],
 [978, 24],
 [1, 794],
 [1, 794],
 [1, 179],
 [1, 191],
 [1, 191],
 [1, 675],
 [1, 112],
 [1, 979],
 [2, 1949],
 [2, 149],
 [2, 149],
 [1270],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [37, 351],
 [795],
 [795],
 [795],
 [500],
 [7, 190],
 [7, 154],
 [7, 154],
 [7, 154],
 [7, 154],
 [123, 47],
 [1950],
 [15, 278],
 [15, 278],
 [15, 278],
 [15, 192],
 [15, 253],
 [15, 253],
 [15, 253],
 [15, 253],
 [15, 253],
 [15, 253],
 [15, 580],
 [15, 193],
 [15, 193],
 [15, 193],
 [15, 193],
 [15, 193],
 [15, 193],
 [796, 12]

In [26]:
m=max([len(text) for text in inp_encds])
print(m)
m=max([len(text) for text in inp_encds])
def zero_padding_and_masking(sequences,max_len):
    batch_size=len(sequences)
    padded_sequences=np.zeros((batch_size,max_len),dtype=np.int32)
    mask=np.zeros((batch_size,max_len))
    for i,seq in enumerate(sequences):
        seq_len=len(seq)
        padded_sequences[i,:seq_len]=seq
        mask[i,:seq_len]=1
    mask[mask==0]=-np.infty
    mask[mask==1]=0
    mask=tf.reshape(mask,(batch_size,1,max_len)) # here we mask shape is (batch_size,seq_len) we reshape it to (batch_size,1,seq_len) or (100000,1,10)  because 
    # the shape of look_ahead_mask will be (batch_size,seq_len,seq_len) or (10000,10,10).hence reshape the padding_mask so that during addition of both array the padding mask will added perfectly with the help of broadcastting
    mask=tf.broadcast_to(mask,(10000,10,10))
    mask=tf.expand_dims(mask,axis=1) # here we expanded mask along the dimension 1 so it will be converted to (batch_size,1,seq_len,seq_len).we do this because when we add the mask to the qk/dk or attention weights the size of attention weights is (batch_size,num_heads,seq_len,seq_len

    return padded_sequences,mask
        
        
        
    
    
inp_encds,padding_mask=zero_padding_and_masking(inp_encds,10)
inp_encds.shape
    

5


(10000, 10)

In [27]:
inp_encds

array([[1262,    0,    0, ...,    0,    0,    0],
       [1263,    0,    0, ...,    0,    0,    0],
       [1263,    0,    0, ...,    0,    0,    0],
       ...,
       [  15,   99,  163, ...,    0,    0,    0],
       [  15,   99,  163, ...,    0,    0,    0],
       [  15,   99,  163, ...,    0,    0,    0]])

In [29]:
padding_mask

<tf.Tensor: shape=(10000, 1, 10, 10), dtype=float64, numpy=
array([[[[  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         ...,
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf]]],


       [[[  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         ...,
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf]]],


       [[[  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         ...,
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
         [  0., -inf, -inf, ..., -inf, -inf, -inf],
      

In [11]:
len(t.word_index)

2946

In [12]:
embedding_dim=d_model=128
vocab_size=10000
embedding_layer=tf.keras.layers.Embedding(vocab_size,embedding_dim)
embedded_tokens=embedding_layer(inp_encds)
print(embedded_tokens.shape)

(10000, 10, 128)


In [13]:
num_heads=8
seq_len=10
dim_head=embedding_dim//num_heads
dim_head

16

In [47]:
class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self,d_model:int,num_heads:int) -> None :
        super().__init__()
        self.d_model=d_model
        self.num_heads=num_heads
        self.wq=Dense(d_model)
        self.wk=Dense(d_model)
        self.wv=Dense(d_model)
        self.dense=Dense(d_model)
        self.d_head=d_model//num_heads

    
    def scaled_dot_product_attention(self,q,k,v,mask):
        a=tf.matmul(q,k,transpose_b=True)
        dk = tf.cast(tf.shape(k)[-1], tf.float32)
        attention_weights=a/tf.math.sqrt(dk)
        if mask is not None:
            attention_weights +=mask
        attention_scores=tf.nn.softmax(attention_weights)
        outputs=tf.matmul(attention_scores,v)
        return outputs,attention_scores

    
    def split_heads(self, x, batch_size,seq_len):
        x = tf.reshape(x, (batch_size,seq_len, self.num_heads, self.d_head))
        return tf.transpose(x, perm=[0, 2, 1, 3])

    
    def call(self,x,mask):
        batch_size=tf.shape(x)[0]
        seq_len=tf.shape(x)[1]
        
        q=self.wq(x)
        k=self.wk(x)
        v=self.wv(x)
        q=self.split_heads(q,batch_size,seq_len)
        k=self.split_heads(k,batch_size,seq_len)
        v=self.split_heads(v,batch_size,seq_len)
        outputs,attention_weights=self.scaled_dot_product_attention(q,k,v,mask)
        attention = tf.transpose(outputs, perm=[0, 2, 1, 3])
        attention = tf.reshape(attention, (batch_size, -1, self.d_model))
        output = self.dense(attention)
        return output

# Instantiate the MultiHeadAttention layer

# Example number of attention heads
mha_layer = MultiHeadAttention(d_model, num_heads)

# Call the layer
output = mha_layer(embedded_tokens,mask=padding_mask)
output

# Now `output` will be the result of the multi-head attention operation


<tf.Tensor: shape=(10000, 10, 128), dtype=float32, numpy=
array([[[ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431],
        [ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431],
        [ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431],
        ...,
        [ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431],
        [ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431],
        [ 0.01944995,  0.02512382,  0.0134644 , ...,  0.0750225 ,
         -0.03779506, -0.02335431]],

       [[ 0.02100766,  0.01510594, -0.03759827, ...,  0.06285175,
         -0.01948562, -0.01524364],
        [ 0.02100766,  0.01510594, -0.03759827, ...,  0.06285175,
         -0.01948562, -0.01524364],
        [ 0.02100766,  0.01510594, -0.03759827, ...,  0.06285175,
         -0.01948562, -0.01524364],
        .

In [15]:
mha_layer.trainable_variables

[<KerasVariable shape=(128, 128), dtype=float32, path=multi_head_attention/dense/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=multi_head_attention/dense/bias>,
 <KerasVariable shape=(128, 128), dtype=float32, path=multi_head_attention/dense_1/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=multi_head_attention/dense_1/bias>,
 <KerasVariable shape=(128, 128), dtype=float32, path=multi_head_attention/dense_2/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=multi_head_attention/dense_2/bias>,
 <KerasVariable shape=(128, 128), dtype=float32, path=multi_head_attention/dense_3/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=multi_head_attention/dense_3/bias>]

In [16]:
class Feedforward(tf.keras.layers.Layer):
    def __init__(self,d_model,dff):
        super().__init__()
        self.d_model=d_model
        self.dff=dff
        self.layer1=tf.keras.layers.Dense(dff,activation="relu")
        self.layer2=tf.keras.layers.Dense(d_model)
    def call(self,x):
        out1=self.layer1(x)
        out2=self.layer2(out1)
        return out2

In [35]:
class Encoder_layer(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads,dff):
        super().__init__()
        self.attention=MultiHeadAttention(d_model=d_model,num_heads=num_heads)
        self.norm_and_add1=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm_and_add2=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.feed_forward=Feedforward(dff=dff,d_model=d_model)
    def call(self,x,mask):
        attention_out=self.attention(x,mask)
        norm_and_add1_out=self.norm_and_add1(x+attention_out)
        feed_forward_out=self.feed_forward(norm_and_add1_out)
        norm_and_add2_out=self.norm_and_add2(norm_and_add1_out+feed_forward_out)
        return norm_and_add2_out

In [49]:
s=Encoder_layer(d_model=128,num_heads=8,dff=1024)
out=s(embedded_tokens,padding_mask)
out

<tf.Tensor: shape=(10000, 10, 128), dtype=float32, numpy=
array([[[-1.3774436 ,  1.4436734 ,  0.14911433, ..., -0.11214082,
         -0.5889169 , -1.1167802 ],
        [ 0.5303944 , -0.42561567,  0.6961518 , ...,  1.5698544 ,
         -1.1315651 ,  0.59566885],
        [ 0.5303944 , -0.42561567,  0.6961518 , ...,  1.5698544 ,
         -1.1315651 ,  0.59566885],
        ...,
        [ 0.5303944 , -0.42561567,  0.6961518 , ...,  1.5698544 ,
         -1.1315651 ,  0.59566885],
        [ 0.5303944 , -0.42561567,  0.6961518 , ...,  1.5698544 ,
         -1.1315651 ,  0.59566885],
        [ 0.5303944 , -0.42561567,  0.6961518 , ...,  1.5698544 ,
         -1.1315651 ,  0.59566885]],

       [[ 0.7749171 , -1.0111914 , -0.44906926, ...,  0.55790603,
         -0.8326873 ,  0.9453273 ],
        [ 0.88190496, -0.9295347 , -0.23406175, ...,  1.9204236 ,
         -0.25279963,  1.10361   ],
        [ 0.88190496, -0.9295347 , -0.23406175, ...,  1.9204236 ,
         -0.25279963,  1.10361   ],
        .

In [68]:
class SequentialEncoder(tf.keras.layers.Layer):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers

    def call(self, x,mask):
        for layer in self.layers:
            x = layer(x,mask)
        return x

"WE CAN ALSO USE TENSORFLOW SEQUENTIAL MODULE TO IMPLEMENT MULTIPLE ENCODER_LAYER BUT BY USING THIS WE CAN ONLY GIVE ONE INPUT FOR THE CALL FUNCTION OF ENCODER_LAYER,BUT WE HAVE TO GIVE X AND THE MASK FOR THE CALL FUNCTION SO WE CREATE A SEQUENTIAL_ENCODER CLASS TO IMPLEMENT THIS

self.layer=tf.keras.models.Sequential([Encoder_layer(d_model,num_heads,dff) for _ in range(self.num_encoders)])
    def call(self,x):
        x=self.layer(x)
        return x
    

In [38]:
"""class Encoder(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads,dff,num_encoders):
        super().__init__()
        self.num_encoders=num_encoders
        self.layer=tf.keras.models.Sequential([Encoder_layer(d_model,num_heads,dff) for _ in range(self.num_encoders)])
    def call(self,x):
        x=self.layer(x)
        return x"""
    

'class Encoder(tf.keras.layers.Layer):\n    def __init__(self,d_model,num_heads,dff,num_encoders):\n        super().__init__()\n        self.num_encoders=num_encoders\n        self.layer=tf.keras.models.Sequential([Encoder_layer(d_model,num_heads,dff) for _ in range(self.num_encoders)])\n    def call(self,x):\n        x=self.layer(x)\n        return x'

In [69]:
class Encoder(tf.keras.layers.Layer):
    def __init__(self, d_model,num_heads,dff,num_encoders):
        super().__init__()
        self.layers = SequentialEncoder([Encoder_layer(d_model=d_model,num_heads=num_heads,dff=dff) for _ in range(num_encoders)])

    def call(self, x,mask):
        x = self.layers(x,mask)
        return x

In [70]:
o=Encoder(d_model=128,num_heads=8,dff=512,num_encoders=12)
d=o(embedded_tokens,mask=padding_mask)
d

<tf.Tensor: shape=(10000, 10, 128), dtype=float32, numpy=
array([[[ 0.21861722,  0.788762  ,  0.3336642 , ..., -0.9623593 ,
          1.1491089 ,  1.0200613 ],
        [ 0.2301639 ,  0.7948818 ,  0.3638682 , ..., -0.9213702 ,
          1.1501882 ,  1.0397338 ],
        [ 0.2301639 ,  0.7948818 ,  0.3638682 , ..., -0.9213702 ,
          1.1501882 ,  1.0397338 ],
        ...,
        [ 0.2301639 ,  0.7948818 ,  0.3638682 , ..., -0.9213702 ,
          1.1501882 ,  1.0397338 ],
        [ 0.2301639 ,  0.7948818 ,  0.3638682 , ..., -0.9213702 ,
          1.1501882 ,  1.0397338 ],
        [ 0.2301639 ,  0.7948818 ,  0.3638682 , ..., -0.9213702 ,
          1.1501882 ,  1.0397338 ]],

       [[ 0.53793514, -0.17244023,  1.9220601 , ..., -0.88373566,
          1.1511203 ,  1.0198456 ],
        [ 0.529103  , -0.16942242,  1.8995075 , ..., -0.8848702 ,
          1.131918  ,  1.0229919 ],
        [ 0.529103  , -0.16942242,  1.8995075 , ..., -0.8848702 ,
          1.131918  ,  1.0229919 ],
        .

In [73]:
o.layers

AttributeError: 'SequentialEncoder' object has no attribute 'q'

In [72]:
len(o.trainable_variables)

192

"THERE ARE ANOTHER TYPES TO IMPLEMENT THE ENCODER THEY ARE":


self.layers = tf.keras.layers.LayerList([ Encoder_layer(seq_len, d_model, num_heads, dff) for _ in range(self.num_encoders) ])
def call(self, x, training=False):
    for layer in self.layers:
        x = layer(x, training=training)
    return x

and  another one will be:

self.layers=[ Encoder_layer(seq_len, d_model, num_heads, dff) for _ in range(self.num_encoders) ]
def call(self, x, training=False):
        for i in range(self.num_encoders) :
            x=self.layers[i](x)
        return x