In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense

In [2]:
START_TOKEN="<start>"
END_TOKEN="<end>"
PADDING_TOKEN=0
telugu_vocabulary = [
     START_TOKEN, ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', 
    '3', '4', '5', '6', '7', '8', '9', ':', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`',
    "అ", "ఆ", "ఇ", "ఈ", "ఉ", "ఊ", "ఋ", "ఌ", "ఎ", "ఏ", "ఐ", "ఒ", "ఓ", "ఔ", "క", "ఖ", "గ", "ఘ", "ఙ", 
    "చ", "ఛ", "జ", "ఝ", "ఞ", "ట", "ఠ", "డ", "ఢ", "ణ", "త", "థ", "ద", "ధ", "న", "ప", "ఫ", "బ", "భ", "మ", 
    "య", "ర", "ఱ", "ల", "ళ", "ఴ", "వ", "శ", "ష", "స", "హ", "ౠ", "◌ా", "◌ి", "◌ీ", "ు", "ూ", "ృ", "ౄ", 
    "◌ె", "◌ే", "◌ై", "◌ొ", "◌ో", "◌ౌ", "◌ౢ", "◌ౣ", ".", "।", "॥", "॰", "◌్", "◌ౕ", "◌ౖ", "◌ఀ", "ఁ",  'ా','ి',
'ీ','ె','ే','ై','ొ','ో', 'ౌ','్','ౖ','౦','౧','౨','౩','౭','౯','ಂ','ಆ','ಕ','ಗ','ಚ','ಜ','ನ','ಬ','ಮ','ರ','ಳ','ಾ','ಿ','ು','ೂ','ೆ','್','ງ','ດ','ທ','ປ','ມ','ລ','ວ','ອ','ະ','າ','ື','ເ','–','—','‘','’','“','”','‡','•','․','…', '′','″',
   
'آ',
 'ئ',
 'ا',
 'ب',
 'ة',
 'ت',
 'د',
 'ر',
 'ز',
 'ش',
 'ض',
 'ع',
 'ف',
 'ق',
 'ل',
 'و',
 'پ',
 'ہ',
 'ی',
 'ं',"ం", "ః", "ॐ", '{', '|', '}', '~' , PADDING_TOKEN, END_TOKEN
]
english_vocabulary = [
    START_TOKEN, ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', 
    '3', '4', '5', '6', '7', '8', '9', ':', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c',
    'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 
    'z', '{', '|', '}', '~', PADDING_TOKEN, END_TOKEN
]


In [3]:
t=set(telugu_vocabulary)
telugu_vocabulary=[k for k in t]

    

In [4]:
telugu_vocabulary

[0,
 'ఉ',
 '6',
 'భ',
 ')',
 'ఢ',
 '?',
 'ఝ',
 'త',
 'ಳ',
 'ວ',
 'آ',
 '=',
 'ಜ',
 'ೂ',
 '్',
 '”',
 '౭',
 '!',
 'ధ',
 'ఊ',
 'ఛ',
 '।',
 'ರ',
 'ఈ',
 'ಿ',
 'శ',
 '◌ఀ',
 '_',
 'డ',
 '◌ై',
 'ທ',
 '‡',
 'ನ',
 'ఞ',
 '․',
 'ద',
 '′',
 '/',
 'ఁ',
 'ఆ',
 'ఱ',
 'ື',
 'ض',
 '“',
 'د',
 '@',
 'ఇ',
 'ఖ',
 '◌ీ',
 '3',
 'ಂ',
 'ປ',
 'ເ',
 'ఠ',
 'ل',
 'ງ',
 '*',
 '౯',
 '4',
 '&',
 'చ',
 'ా',
 'ం',
 '◌ో',
 '◌ౌ',
 '>',
 'ౠ',
 'ు',
 'ే',
 'ూ',
 'ة',
 'າ',
 'ప',
 '"',
 'ఘ',
 'ట',
 ',',
 '◌ౣ',
 'ಾ',
 'ಮ',
 'ق',
 '-',
 'ಚ',
 '2',
 'ర',
 'ౄ',
 '{',
 '~',
 'ణ',
 ']',
 'ع',
 'ౖ',
 'و',
 '౩',
 '◌ి',
 '◌్',
 'ೆ',
 '౧',
 'ئ',
 '◌ౢ',
 'ं',
 'న',
 '◌ా',
 'ె',
 'ز',
 'అ',
 '}',
 '|',
 '…',
 'ృ',
 '◌ొ',
 '+',
 'ీ',
 'ఎ',
 'ఔ',
 'బ',
 'ి',
 'ಆ',
 '[',
 'ష',
 'ش',
 '(',
 '9',
 '<',
 '^',
 'స',
 '•',
 '౨',
 '5',
 'ॐ',
 'య',
 'ು',
 'ొ',
 '0',
 'ఒ',
 '%',
 '◌ౕ',
 'ت',
 'ఓ',
 'ہ',
 'پ',
 '\\',
 'గ',
 'ر',
 '್',
 ':',
 '॰',
 'ఙ',
 'ಗ',
 '8',
 'ళ',
 'ب',
 '◌ౖ',
 'థ',
 'ఏ',
 'ಬ',
 '–',
 'ఴ',
 'ః',
 'ະ',
 '1',
 'జ',
 'ో',
 "'"

In [5]:

with open("C:/Users/nchar/Desktop/eng-to-tel_translation/train_en.txt", 'r',encoding="utf-8") as file:
    english_sentences = file.readlines()
with open("C:/Users/nchar/Desktop/eng-to-tel_translation/train_te.txt", 'r',encoding="utf_8") as file:
    telugu_sentences = file.readlines()

english_sentences

['Rise again.\n',
 'How do we glorify Jehovahs undeserved kindness?\n',
 'India also continues to push back economically.\n',
 'I remember my childhood days.\n',
 'All transactions are made online.\n',
 'I love night shoots in my city.\n',
 'Three members of a family were killed in the incident.\n',
 'The film is directed by V V Vinayak.\n',
 'The Hyderabad weather office forecast more rains.\n',
 'We are family!\n',
 'In this context, the Rs.\n',
 'What is the phrase?\n',
 'In Monaco-Ville, street signs are printed in both French and Mongasque.\n',
 'The same has been confirmed in a report carried by BBC.\n',
 "I said, 'who are you?'\n",
 'In this state they can easily survive one year or longer.\n',
 'The complete details of his death are yet to be known.\n',
 'If You Go...\n',
 '"All the very best."""\n',
 'What is this, child?\n',
 'Speaking during another Session on Reducing poverty through social and economic transformation, Shri Gangwar the Government of India, under the leaders

In [6]:
index_to_telugu = {k:v for k,v in enumerate(telugu_vocabulary)}
telugu_to_index = {v:k for k,v in enumerate(telugu_vocabulary)}
index_to_english = {k:v for k,v in enumerate(english_vocabulary)}
english_to_index = {v:k for k,v in enumerate(english_vocabulary)}

In [7]:
telugu_to_index[PADDING_TOKEN]

0

In [8]:
PERCENTILE = 97
print( f"{PERCENTILE}th percentile length telugu: {np.percentile([len(x) for x in telugu_sentences], PERCENTILE)}" )
print( f"{PERCENTILE}th percentile length English: {np.percentile([len(x) for x in english_sentences], PERCENTILE)}" )

97th percentile length telugu: 169.0
97th percentile length English: 177.0


In [9]:
TOTAL_SENTENCES = 10000
english_sentences = english_sentences[:TOTAL_SENTENCES]
telugu_sentences = telugu_sentences[:TOTAL_SENTENCES]
english_sentences = [sentence.rstrip('\n').lower() for sentence in english_sentences]
telugu_sentences = [sentence.rstrip('\n') for sentence in telugu_sentences]
     

telugu_sentences[:10]

['మళ్లీ ఉదయిస్తాడు.',
 'యెహోవా కృపను మనమెలా మహిమపరచవచ్చు?',
 'ఆర్థికంగా కూడా భారత్\u200c వే గంగా పయనిస్తున్నది.',
 '‘విద్యార్థులను చూస్తుంటే నాకు చిన్నప్పటి రోజులు గుర్తుకొస్తున్నాయి.',
 'ఆర్థిక లావాదేవీలన్నీ ఆన్\u200cలైన్\u200cలోనే',
 'పద్మినీ స్త్రీ రాత్రి వేళల్లో రతికి ఇష్టపడదు.',
 'ఓకే కుటుంబానికి చెందిన ముగ్గురు మృతిచెందటంతో ఈ సంఘటన కలవరపర్చింది.',
 'ఆ సినిమాకు వి. వి. వినాయక్\u200c దర్శకత్వం వహించనున్నారు.',
 'హైదరాబాద్\u200cకు మరో భారీ వర్షం సూచనలున్నాయని వాతావరణ శాఖ హెచ్చరించింది.',
 'మనం అంటున్న మమ్ముట్టి ఫ్యామిలీ !']

In [10]:
# Replace specific unwanted characters
telugu_sentences = [sentence.replace('\u200B', '').replace('\u200C', '').replace('\u200D', '') for sentence in telugu_sentences]


In [11]:
max_sequence_length = 200

def is_valid_tokens(sentence, vocab):
    l=set()
    for token in list(set(sentence)):
        if token not in vocab:
            l.add(token)
    return l

def is_valid_length(sentence, max_sequence_length):
    return len(list(sentence)) < (max_sequence_length - 1) # need to re-add the end token so leaving 1 space


p=set()
for index in range(len(telugu_sentences)):
    telugu_sentence, english_sentence = telugu_sentences[index], english_sentences[index]
    a=is_valid_tokens(telugu_sentence, telugu_vocabulary)
    for i in a:
        p.add(i)


In [12]:
index=[]
for i in range(len(telugu_sentences)):
    if( is_valid_length(telugu_sentences[i],200)and is_valid_length(english_sentences[i],200)):
        index.append(i)

In [13]:
telugu_sentences = [telugu_sentences[i] for i in index]
english_sentences = [english_sentences[i] for i in index]

In [14]:
len(telugu_sentences)

9776

In [15]:
len(english_sentences)

9776

In [16]:
s=[]
for sentence in telugu_sentences:
    b=sentence
    for a in p:
        if a in b:
            b=b.replace(a,"")
    s.append(b)
len(s)

9776

In [17]:
telugu_cleaned_sentences=s
telugu_cleaned_sentences[:10]

['మళ్లీ ఉదయిస్తాడు.',
 'యెహోవా కృపను మనమెలా మహిమపరచవచ్చు?',
 'ఆర్థికంగా కూడా భారత్ వే గంగా పయనిస్తున్నది.',
 '‘విద్యార్థులను చూస్తుంటే నాకు చిన్నప్పటి రోజులు గుర్తుకొస్తున్నాయి.',
 'ఆర్థిక లావాదేవీలన్నీ ఆన్లైన్లోనే',
 'పద్మినీ స్త్రీ రాత్రి వేళల్లో రతికి ఇష్టపడదు.',
 'ఓకే కుటుంబానికి చెందిన ముగ్గురు మృతిచెందటంతో ఈ సంఘటన కలవరపర్చింది.',
 'ఆ సినిమాకు వి. వి. వినాయక్ దర్శకత్వం వహించనున్నారు.',
 'హైదరాబాద్కు మరో భారీ వర్షం సూచనలున్నాయని వాతావరణ శాఖ హెచ్చరించింది.',
 'మనం అంటున్న మమ్ముట్టి ఫ్యామిలీ !']

In [18]:
len(telugu_cleaned_sentences)

9776

In [19]:

class TextDataset:

    def __init__(self, english_sentences, telugu_cleaned_sentences):
        self.english_sentences = english_sentences
        self.telugu_sentences = telugu_cleaned_sentences

    def __len__(self):
        return len(self.english_sentences)

    def __getitem__(self, idx):
        return self.english_sentences[idx], self.telugu_sentences[idx]

    def to_tf_dataset(self, batch_size=32, shuffle=True):
        # Create a TensorFlow dataset from the sentence pairs
        dataset = tf.data.Dataset.from_tensor_slices((self.english_sentences, self.telugu_sentences))
        
        if shuffle:
            dataset = dataset.shuffle(buffer_size=len(self.english_sentences))

        # Batch the dataset
        dataset = dataset.batch(batch_size)

        # Prefetch to improve performance
        dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

        return dataset


In [20]:
dataset = TextDataset(english_sentences,telugu_cleaned_sentences)

In [21]:
batch_size=32
tf_dataset = dataset.to_tf_dataset(batch_size=batch_size)

In [22]:
len(tf_dataset)

306

In [23]:
ex_dataset=tf_dataset.take(3)

In [24]:
# Create an iterator
iterator = iter(ex_dataset.as_numpy_iterator())

# Fetch the next batch
batch = next(iterator)
batch[0][0]

b'this is a must do.'

In [25]:
d_model=128
batch_size=32
num_heads=8
english_max_length=telugu_max_length=200

In [26]:
NEG_INFTY = -1e9

def create_masks(eng_batch, tel_batch,max_sequence_length):
    num_sentences = len(eng_batch)
    look_ahead_mask = np.full([max_sequence_length, max_sequence_length] , True)
    look_ahead_mask = np.triu(look_ahead_mask,1)
    encoder_padding_mask = np.full([num_sentences, max_sequence_length, max_sequence_length] , False)
    decoder_padding_mask_self_attention = np.full([num_sentences, max_sequence_length, max_sequence_length] , False)
    decoder_padding_mask_cross_attention = np.full([num_sentences, max_sequence_length, max_sequence_length] , False)

    for idx in range(num_sentences):
        #eng_sentence_length, tel_sentence_length = tf.shape(eng_batch[idx])[0], tf.shape(tel_batch[idx])[0]
        eng_sentence_length, tel_sentence_length = len(eng_batch[idx]),len(tel_batch[idx])
        eng_chars_to_padding_mask = np.arange(eng_sentence_length + 1, max_sequence_length)
        tel_chars_to_padding_mask = np.arange(tel_sentence_length + 1, max_sequence_length)
        encoder_padding_mask[idx, :, eng_chars_to_padding_mask] = True
        encoder_padding_mask[idx, eng_chars_to_padding_mask, :] = True
        decoder_padding_mask_self_attention[idx, :, tel_chars_to_padding_mask] = True
        decoder_padding_mask_self_attention[idx, tel_chars_to_padding_mask, :] = True
        decoder_padding_mask_cross_attention[idx, :, eng_chars_to_padding_mask] = True
        decoder_padding_mask_cross_attention[idx, tel_chars_to_padding_mask, :] = True

    encoder_self_attention_mask = tf.convert_to_tensor(np.where(encoder_padding_mask, NEG_INFTY, 0))
    decoder_self_attention_mask =  tf.convert_to_tensor(np.where(look_ahead_mask + decoder_padding_mask_self_attention, NEG_INFTY, 0))
    decoder_cross_attention_mask = tf.convert_to_tensor(np.where(decoder_padding_mask_cross_attention, NEG_INFTY, 0))
    encoder_self_attention_mask=tf.expand_dims(encoder_self_attention_mask,axis=1)
    decoder_self_attention_mask=tf.expand_dims(decoder_self_attention_mask,axis=1)
    decoder_cross_attention_mask=tf.expand_dims(decoder_cross_attention_mask,axis=1)
    return encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask

In [27]:
def create_masks1(eng_batch, tel_batch, max_sequence_length=200):
    # Get the batch size (number of sentences)
    num_sentences = tf.shape(eng_batch)[0]

    # Look-ahead mask for self-attention in the decoder
    look_ahead_mask = tf.linalg.band_part(tf.ones((max_sequence_length, max_sequence_length)), -1, 0)  # Upper triangular matrix
    look_ahead_mask = tf.cast(look_ahead_mask, dtype=tf.float32)

    # Padding masks (initialize with False)
    encoder_padding_mask = tf.fill([num_sentences, max_sequence_length], False)
    decoder_padding_mask_self_attention = tf.fill([num_sentences, max_sequence_length], False)
    decoder_padding_mask_cross_attention = tf.fill([num_sentences, max_sequence_length], False)

    # Expand dimensions to match required shape
    encoder_padding_mask = tf.expand_dims(encoder_padding_mask, axis=1)  # Shape: [num_sentences, 1, max_sequence_length]
    decoder_padding_mask_self_attention = tf.expand_dims(decoder_padding_mask_self_attention, axis=1)
    decoder_padding_mask_cross_attention = tf.expand_dims(decoder_padding_mask_cross_attention, axis=1)

    # Broadcast to the required shapes
    encoder_self_attention_mask = tf.broadcast_to(encoder_padding_mask, [num_sentences, max_sequence_length, max_sequence_length])
    decoder_self_attention_mask = tf.broadcast_to(decoder_padding_mask_self_attention, [num_sentences, max_sequence_length, max_sequence_length])
    decoder_cross_attention_mask = tf.broadcast_to(decoder_padding_mask_cross_attention, [num_sentences, max_sequence_length, max_sequence_length])

    return encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask

In [28]:
eng,tel=batch
encoder_self_attention_mask,decoder_self_attention_mask,decoder_cross_attention_mask=create_masks(eng,tel,telugu_max_length)

In [29]:
for idx in range(len(eng)):
    p=len(eng[idx])
p

12

In [30]:
eng,tel=batch
encoder_self_attention_mask1,decoder_self_attention_mask1,decoder_cross_attention_mask1=create_masks1(eng,tel,telugu_max_length)

In [31]:
type(tel)

numpy.ndarray

In [29]:
encoder_self_attention_mask.shape,decoder_self_attention_mask.shape,decoder_cross_attention_mask.shape

(TensorShape([32, 1, 200, 200]),
 TensorShape([32, 1, 200, 200]),
 TensorShape([32, 1, 200, 200]))

In [33]:
encoder_self_attention_mask1.shape,decoder_self_attention_mask1.shape,decoder_cross_attention_mask1.shape

(TensorShape([32, 200, 200]),
 TensorShape([32, 200, 200]),
 TensorShape([32, 200, 200]))

In [34]:
encoder_self_attention_mask1[0][0]

<tf.Tensor: shape=(200,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, Fal

In [35]:
encoder_self_attention_mask[0][0][0]

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([ 0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,  0.e+00,
        0.e+00,  0.e+00,  0.e+00,  0.e+00, -1.e+09, -1.e+09, -1.e+09,
       -1.e+09, -1.e+09, -1.e+09, -1.e+09,

In [30]:
class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self,d_model:int,num_heads:int) -> None :
        super().__init__()
        self.d_model=d_model
        self.num_heads=num_heads
        self.wq=Dense(d_model)
        self.wk=Dense(d_model)
        self.wv=Dense(d_model)
        self.dense=Dense(d_model)
        self.d_head=d_model//num_heads

    
    def scaled_dot_product_attention(self,q,k,v,mask):
        a=tf.matmul(q,k,transpose_b=True)
        dk = tf.cast(tf.shape(k)[-1], tf.float32)
        attention_weights=a/tf.math.sqrt(dk)
        if mask is not None:
            mask = tf.cast(mask, dtype=tf.float32)
            attention_weights +=mask
        attention_scores=tf.nn.softmax(attention_weights)
        outputs=tf.matmul(attention_scores,v)
        return outputs,attention_scores

    
    def split_heads(self, x, batch_size,seq_len):
        if tf.shape(x)[-1] % self.num_heads != 0:
            raise ValueError("The last dimension of the input tensor must be divisible by num_heads.")
    
        x = tf.reshape(x, (batch_size,seq_len, self.num_heads, self.d_head))
        return tf.transpose(x, perm=[0, 2, 1, 3])

    
    def call(self,x,mask):
        batch_size=tf.shape(x)[0]
        seq_len=tf.shape(x)[1]
        
        q=self.wq(x)
        k=self.wk(x)
        v=self.wv(x)
        q=self.split_heads(q,batch_size,seq_len)
        k=self.split_heads(k,batch_size,seq_len)
        v=self.split_heads(v,batch_size,seq_len)
        outputs,attention_weights=self.scaled_dot_product_attention(q,k,v,mask)
        attention = tf.transpose(outputs, perm=[0, 2, 1, 3])
        attention = tf.reshape(attention, (batch_size, -1, self.d_model))
        output = self.dense(attention)
        return output

# Instantiate the MultiHeadAttention layer

# Example number of attention heads
#mha_layer = MultiHeadAttention(d_model, num_heads)

# Call the layer
#output = mha_layer(english_embedded_tokens,mask=english_padding_mask)
#output

# Now `output` will be the result of the multi-head attention operation


In [31]:
class Feedforward(tf.keras.layers.Layer):
    def __init__(self,d_model,dff):
        super().__init__()
        self.d_model=d_model
        self.dff=dff
        self.layer1=tf.keras.layers.Dense(dff,activation="relu")
        self.layer2=tf.keras.layers.Dense(d_model)
    def call(self,x):
        out1=self.layer1(x)
        out2=self.layer2(out1)
        return out2

In [32]:
class CrossMultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads):
        super().__init__()
        self.num_heads=num_heads
        self.d_model=d_model
        self.wq=tf.keras.layers.Dense(d_model)
        self.wk=tf.keras.layers.Dense(d_model)
        self.wv=tf.keras.layers.Dense(d_model)
        self.dense=tf.keras.layers.Dense(d_model)
        self.d_head=d_model//num_heads


    def split_heads(self,y,batch_size,seq_len):
        if tf.shape(y)[-1] % self.num_heads != 0:
            raise ValueError("The last dimension of the input tensor must be divisible by num_heads.")
        y=tf.reshape(y,(batch_size,seq_len,self.num_heads,self.d_head))
        y=tf.transpose(y,perm=[0,2,1,3])
        return y


    def scaled_dot_product_attention(self,q,k,v,mask):
        qk=tf.matmul(q,k,transpose_b=True)
        dk=float(tf.shape(k)[-1])
        attention_weights=qk/tf.math.sqrt(dk)
        if mask is not None:
            attention_weights +=mask
        attention_score=tf.nn.softmax(attention_weights)
        output=tf.matmul(attention_score,v)
        return output


    def call(self,x,y,mask):
        q=self.wq(y)
        k=self.wk(x)
        v=self.wv(x)
        batch_size=tf.shape(y)[0]
        seq_len=tf.shape(y)[1]
        q=self.split_heads(q,batch_size,seq_len)
        k=self.split_heads(k,batch_size,seq_len)
        v=self.split_heads(v,batch_size,seq_len)
        attention=self.scaled_dot_product_attention(q,k,v,mask)
        output=tf.transpose(attention,perm=[0,2,1,3])
        final_output=tf.reshape(output,(batch_size,-1,self.d_model))
        return final_output
 

In [33]:

class SentenceEmbedding(tf.keras.layers.Layer):
    "For a given sentence, create an embedding"
    def __init__(self, max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.max_sequence_length = max_sequence_length
        self.embedding = tf.keras.layers.Embedding(self.vocab_size, d_model)
        self.language_to_index = language_to_index
        self.d_model=d_model
        #self.position_encoder = PositionalEncoding(d_model, max_sequence_length)
        self.dropout = tf.keras.layers.Dropout(rate=0.1)
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.PADDING_TOKEN = PADDING_TOKEN
    def decoding(self,batch):
       # batch=np.array(batch)
        decoded_list=[]
        #b=batch.numpy()
        #batch=tf.make_ndarray(batch)
        for i in (batch):
            p=i.decode("utf-8")
            #p=p.tolist()
            #p=np.array(p)
            decoded_list.append(p)
        return decoded_list
  
    def position_encoder(self):
        # Create the positional encodings with shape (max_sequence_length, d_model)
        pos = np.arange(self.max_sequence_length)[:, np.newaxis]
        i = np.arange(self.d_model)[np.newaxis, :]
        
        # Positional encoding formula used in Transformer models
        angle_rads = pos / np.power(10000, (2 * (i // 2)) / np.float32(self.d_model))
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])  # Apply sin to even indices
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])  # Apply cos to odd indices
        
        pos_encoding = angle_rads[np.newaxis, ...]  # Add batch dimension
        return tf.cast(pos_encoding, dtype=tf.float32)
    def batch_tokenize(self, batch, start_token, end_token):
        
        OOV_TOKEN = self.language_to_index.get("<unk>", self.vocab_size - 1)
        def tokenize(sentence, start_token, end_token):
            #z=sentence[np.newaxis,...]
            #sentence=z[0]
            #if isinstance(sentence, str):
                #sentence = list(sentence)
            #sentence=sentence[np.newaxis,...]
            #sentence=sentence[0]
            sentence_word_indicies = [self.language_to_index.get(token, OOV_TOKEN) for token in list(sentence[:self.max_sequence_length])]
            if start_token:
                sentence_word_indicies.insert(0, self.language_to_index[self.START_TOKEN])
            if end_token:
                sentence_word_indicies.append(self.language_to_index[self.END_TOKEN])
            for _ in range(len(sentence_word_indicies), self.max_sequence_length):
                sentence_word_indicies.append(self.language_to_index[self.PADDING_TOKEN])
            return tf.convert_to_tensor(sentence_word_indicies[:self.max_sequence_length])

        tokenized = []
        for sentence in batch:
           tokenized.append( tokenize(sentence, start_token, end_token) )
        tokenized = tf.stack(tokenized)
        return tokenized
    
    def call(self, x, start_token, end_token): # sentence
        """if isinstance(x, list):
        # Convert list elements to NumPy array only if their shapes are consistent
            x = [tensor.numpy() if hasattr(tensor, 'numpy') else tensor for tensor in x]

    # If all tensors are consistent, you can convert them to a single array
        try:
            x = np.array(x)
        except ValueError as e:
            print(f"Error converting x to a NumPy array: {e}")
        # Handle error, possibly by checking or reshaping elements"""
        print("shape of x=",x.shape)
        #print(type(x[0]))
    # Continue with your decoding logic
        x = self.decoding(batch=np.array(x))
        #x=self.decoding(batch=np.array(x))
        
        x = self.batch_tokenize(x, start_token, end_token)
        
        x = self.embedding(x)
        pos = self.position_encoder()
        x = self.dropout(x + pos)
        return x

In [41]:
k=d

aaa=[e for e in k]
z=aaa[0][np.newaxis,...]
z[0][0]

NameError: name 'd' is not defined

In [ ]:
def decoding(batch):
    decoded_list=[]
        #b=batch.numpy()
        #batch=tf.make_ndarray(batch)
    for i in (batch):
        p=i.decode("utf-8")
            #p=p.tolist()
        p=np.array(p)
        decoded_list.append(p)
    return decoded_list
bat=decoding(batch[1])
decoder = build_decoder(num_layers=12, d_model=d_model, num_heads=8, dff=512,max_sequence_length=200,language_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
output = decoder([encoder_out, batch[1], decoder_self_attention_mask, decoder_cross_attention_mask])

In [ ]:
bat

In [34]:
class Encoder_layer(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads,dff):
        super().__init__()
        self.attention=MultiHeadAttention(d_model=d_model,num_heads=num_heads)
        self.norm_and_add1=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm_and_add2=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.feed_forward=Feedforward(dff=dff,d_model=d_model)
    def call(self,x,mask):
        attention_out=self.attention(x=x,mask=mask)
        norm_and_add1_out=self.norm_and_add1(x+attention_out)
        feed_forward_out=self.feed_forward(norm_and_add1_out)
        norm_and_add2_out=self.norm_and_add2(norm_and_add1_out+feed_forward_out)
        return norm_and_add2_out

In [35]:
class SequentialEncoder(tf.keras.layers.Layer):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers

    def call(self, x,mask):
        for layer in self.layers:
            x = layer(x,mask=mask)
        return x

In [36]:
class Encoder(tf.keras.layers.Layer):
    def __init__(self, d_model,num_heads,dff,num_encoders,max_sequence_length,language_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN):
        super().__init__()
        self.sentence_embedding=SentenceEmbedding(max_sequence_length=max_sequence_length, d_model=d_model, language_to_index=language_to_index, START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
        self.layers = SequentialEncoder([Encoder_layer(d_model=d_model,num_heads=num_heads,dff=dff) for _ in range(num_encoders)])

    def call(self, x,mask,start_token,end_token):
        x=self.sentence_embedding(x=x,start_token=start_token,end_token=end_token)
        x = self.layers(x=x,mask=mask)
        return x

In [37]:
s=Encoder(d_model=d_model,num_heads=num_heads,dff=512,num_encoders=12,max_sequence_length=english_max_length,language_to_index=english_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)


In [38]:
# Create an iterator
iterator = iter(ex_dataset.as_numpy_iterator())

# Fetch the next batch
batch = next(iterator)
batch[0][0]

b'the award in different categories were also given to the winners.'

In [39]:
encoder_out=[]
for inputs, targets in ex_dataset.as_numpy_iterator():
    out=s(inputs,mask=encoder_self_attention_mask,start_token=True,end_token=True)
    encoder_out.append(out)

shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)


In [40]:
encoder_out

[<tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
 array([[[-0.5564932 , -0.5669649 ,  0.7027901 , ..., -0.53199303,
          -1.3212402 , -0.776253  ],
         [-0.5504785 , -0.5705082 ,  0.70116484, ..., -0.53427404,
          -1.3195268 , -0.7772775 ],
         [-0.5492785 , -0.5775336 ,  0.70136094, ..., -0.53291005,
          -1.3175031 , -0.7803993 ],
         ...,
         [-0.5963789 , -0.5895573 ,  0.7945759 , ..., -0.74501467,
          -0.8226432 , -0.9577145 ],
         [-0.597221  , -0.5872512 ,  0.8022083 , ..., -0.74653566,
          -0.8225584 , -0.9655758 ],
         [-0.593818  , -0.58298   ,  0.8040438 , ..., -0.74689496,
          -0.81762546, -0.9732748 ]],
 
        [[-1.0716151 , -0.2758856 ,  0.7731406 , ..., -0.2441194 ,
          -0.50318444, -0.5990235 ],
         [-1.0653529 , -0.28005248,  0.7748195 , ..., -0.2476363 ,
          -0.4986616 , -0.60288435],
         [-1.0666635 , -0.28257647,  0.77536714, ..., -0.24508333,
          -0.4984641 , -0.6

In [ ]:
type(np.char.decode(batch[1][0]))

In [41]:
class Decoder_layer(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads,dff):
        super().__init__()
        self.d_model=d_model
        self.num_heads=num_heads
        self.dff=dff
        self.attention=MultiHeadAttention(d_model=d_model,num_heads=num_heads)
        self.norm_and_add1=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm_and_add2=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.encoder_decoder_attention=CrossMultiHeadAttention(d_model=d_model,num_heads=num_heads)
        self.feed_forward=Feedforward(dff=dff,d_model=d_model)
        self.norm_and_add3=tf.keras.layers.LayerNormalization(epsilon=1e-6)
    def call(self,x,y,self_attention_mask,cross_attention_mask): #x==>encoder's final query vector(output)
        attention_out=self.attention(y,mask=self_attention_mask)
        norm_and_add1_out=self.norm_and_add1(attention_out+y)
        encoder_decoder_attention_out=self.encoder_decoder_attention(x,y,mask=cross_attention_mask)
        norm_and_add2_out=self.norm_and_add2(norm_and_add1_out+encoder_decoder_attention_out)
        feed_forward_out=self.feed_forward(norm_and_add2_out)
        norm_and_add3_out=self.norm_and_add3(norm_and_add2_out+feed_forward_out)
        return norm_and_add3_out    

In [42]:
class SequentialDecoder(tf.keras.layers.Layer):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers

    def call(self, x,y,self_attention_mask,cross_attention_mask):
        for layer in self.layers:
            x = layer(x,y,self_attention_mask,cross_attention_mask)
        return x

In [43]:
class DecoderWrapper(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff,max_sequence_length,language_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN):
        super(DecoderWrapper, self).__init__()
        self.sentence_embedding=SentenceEmbedding(max_sequence_length=max_sequence_length, d_model=d_model, language_to_index=language_to_index, START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
        self.decoder_layer = Decoder_layer(d_model, num_heads, dff)

    def call(self, inputs):
        x = inputs[0]
        y=inputs[1]
        self_attention_mask=inputs[2]
        cross_attention_mask=inputs[3]
        
        
        y=self.sentence_embedding(x=y,start_token=True,end_token=True)
        return self.decoder_layer(x=x, y=y, self_attention_mask=self_attention_mask, cross_attention_mask=cross_attention_mask)


In [44]:
def build_decoder(num_layers, d_model, num_heads, dff,max_sequence_length,language_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN):
    decoder = tf.keras.Sequential()
    
    # Add 12 decoder layers
    for _ in range(num_layers):
        decoder.add(DecoderWrapper(d_model, num_heads, dff,max_sequence_length,language_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN))
    
    return decoder


In [45]:
decoder = build_decoder(num_layers=12, d_model=d_model, num_heads=8, dff=512,max_sequence_length=200,language_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
output = decoder([encoder_out, batch[1], decoder_self_attention_mask, decoder_cross_attention_mask])


shape of x= (32,)
shape of x= (32,)


C:\Users\nchar\anaconda\Lib\site-packages\keras\src\layers\layer.py:1383: UserWarning: Layer 'decoder_layer' looks like it has unbuilt state, but Keras is not able to trace the layer `call()` in order to build it automatically. Possible causes:
1. The `call()` method of your layer may be crashing. Try to `__call__()` the layer eagerly on some test input first to see if it works. E.g. `x = np.random.random((3, 4)); y = layer(x)`
2. If the `call()` method is correct, then you may need to implement the `def build(self, input_shape)` method on your layer. It should create all variables used by the layer (e.g. by calling `layer.build()` on all its children layers).
Exception encountered: ''Exception encountered when calling MultiHeadAttention.call().

Using a symbolic `tf.Tensor` as a Python `bool` is not allowed. You can attempt the following resolutions to the problem: If you are running in Graph mode, use Eager execution mode or decorate this function with @tf.function. If you are using 

shape of x= (32,)


C:\Users\nchar\anaconda\Lib\site-packages\keras\src\layers\layer.py:1383: UserWarning: Layer 'cross_multi_head_attention' looks like it has unbuilt state, but Keras is not able to trace the layer `call()` in order to build it automatically. Possible causes:
1. The `call()` method of your layer may be crashing. Try to `__call__()` the layer eagerly on some test input first to see if it works. E.g. `x = np.random.random((3, 4)); y = layer(x)`
2. If the `call()` method is correct, then you may need to implement the `def build(self, input_shape)` method on your layer. It should create all variables used by the layer (e.g. by calling `layer.build()` on all its children layers).
Exception encountered: ''Layer "dense_77" expects 1 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
array([[[-0.5564932 , -0.5669649 ,  0.7027901 , ..., -0.53199303,
         -1.3212402 , -0.776253  ],
        [-0.5504785 , -0.5705082 ,  0.70116484,

ValueError: Exception encountered when calling CrossMultiHeadAttention.call().

Layer "dense_77" expects 1 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
array([[[-0.5564932 , -0.5669649 ,  0.7027901 , ..., -0.53199303,
         -1.3212402 , -0.776253  ],
        [-0.5504785 , -0.5705082 ,  0.70116484, ..., -0.53427404,
         -1.3195268 , -0.7772775 ],
        [-0.5492785 , -0.5775336 ,  0.70136094, ..., -0.53291005,
         -1.3175031 , -0.7803993 ],
        ...,
        [-0.5963789 , -0.5895573 ,  0.7945759 , ..., -0.74501467,
         -0.8226432 , -0.9577145 ],
        [-0.597221  , -0.5872512 ,  0.8022083 , ..., -0.74653566,
         -0.8225584 , -0.9655758 ],
        [-0.593818  , -0.58298   ,  0.8040438 , ..., -0.74689496,
         -0.81762546, -0.9732748 ]],

       [[-1.0716151 , -0.2758856 ,  0.7731406 , ..., -0.2441194 ,
         -0.50318444, -0.5990235 ],
        [-1.0653529 , -0.28005248,  0.7748195 , ..., -0.2476363 ,
         -0.4986616 , -0.60288435],
        [-1.0666635 , -0.28257647,  0.77536714, ..., -0.24508333,
         -0.4984641 , -0.60864574],
        ...,
        [-0.95376545, -0.418268  ,  0.74574107, ..., -0.29118237,
         -0.48366913, -0.66796774],
        [-0.953626  , -0.41489792,  0.7536282 , ..., -0.29210618,
         -0.4839762 , -0.6762593 ],
        [-0.95157635, -0.4086093 ,  0.75293446, ..., -0.2897909 ,
         -0.47764733, -0.6873007 ]],

       [[-1.1036644 , -0.29608777,  0.3539137 , ..., -0.22033647,
         -0.9865732 , -0.61869943],
        [-1.0980034 , -0.30049735,  0.35581362, ..., -0.21943542,
         -0.9875603 , -0.6290449 ],
        [-1.098436  , -0.30892813,  0.36000466, ..., -0.21410285,
         -0.98741204, -0.6310431 ],
        ...,
        [-0.9463632 , -0.44642133,  0.65228087, ..., -0.4215969 ,
         -0.65154004, -0.73296416],
        [-0.946982  , -0.4444359 ,  0.660287  , ..., -0.42369854,
         -0.6534946 , -0.7414886 ],
        [-0.9444964 , -0.4419547 ,  0.6603018 , ..., -0.42320052,
         -0.6461147 , -0.7519346 ]],

       ...,

       [[-1.0963136 , -0.2831757 ,  0.35535613, ..., -0.22245017,
         -1.0090137 , -0.6038814 ],
        [-1.0876743 , -0.29044205,  0.35734963, ..., -0.2208549 ,
         -1.0095688 , -0.6147335 ],
        [-1.0912772 , -0.30087072,  0.3634855 , ..., -0.21891679,
         -1.0094115 , -0.6194747 ],
        ...,
        [-0.926625  , -0.4515016 ,  0.6608705 , ..., -0.4291912 ,
         -0.68744224, -0.7273532 ],
        [-0.92657   , -0.4487603 ,  0.6688588 , ..., -0.43109015,
         -0.6893635 , -0.73599356],
        [-0.92449576, -0.44604528,  0.669178  , ..., -0.43052572,
         -0.6832953 , -0.74667406]],

       [[-0.6454124 , -0.55266553,  0.4279716 , ..., -0.58495647,
         -1.3117238 , -0.81108385],
        [-0.63658184, -0.5600198 ,  0.42756557, ..., -0.5867606 ,
         -1.3126708 , -0.8165589 ],
        [-0.6299888 , -0.5714087 ,  0.422724  , ..., -0.5840041 ,
         -1.3129405 , -0.813739  ],
        ...,
        [-0.6381163 , -0.58815753,  0.7101538 , ..., -0.6911451 ,
         -0.87402123, -0.9569501 ],
        [-0.6389358 , -0.58500224,  0.71641564, ..., -0.6921726 ,
         -0.87369347, -0.9649032 ],
        [-0.63708645, -0.5797171 ,  0.71769357, ..., -0.6921948 ,
         -0.8667831 , -0.9746592 ]],

       [[-1.1142294 , -0.16002925,  0.7755542 , ..., -0.3508806 ,
         -0.27412137, -0.6295667 ],
        [-1.1117277 , -0.16580972,  0.77586204, ..., -0.3538963 ,
         -0.27194566, -0.6377784 ],
        [-1.1156627 , -0.17017971,  0.77920425, ..., -0.3509979 ,
         -0.26812497, -0.64133006],
        ...,
        [-0.9439502 , -0.392971  ,  0.72745097, ..., -0.44148955,
         -0.32154745, -0.7001404 ],
        [-0.945312  , -0.38865873,  0.7332847 , ..., -0.44255903,
         -0.3203026 , -0.70856196],
        [-0.9431359 , -0.38002738,  0.7309662 , ..., -0.44067767,
         -0.31355208, -0.71790135]]], dtype=float32)>, <tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
array([[[-0.5866157 , -0.5525143 ,  0.70000744, ..., -0.49493462,
         -1.3337783 , -0.7703441 ],
        [-0.58179665, -0.5568265 ,  0.6987454 , ..., -0.49723658,
         -1.331469  , -0.772033  ],
        [-0.57948536, -0.56452274,  0.69822353, ..., -0.49449956,
         -1.3299285 , -0.7755725 ],
        ...,
        [-0.62534297, -0.57572025,  0.78345937, ..., -0.7082344 ,
         -0.81456435, -0.94572085],
        [-0.6262148 , -0.5740037 ,  0.79101306, ..., -0.7097448 ,
         -0.8149357 , -0.9541949 ],
        [-0.6229073 , -0.5701721 ,  0.79223526, ..., -0.71076685,
         -0.8087758 , -0.962453  ]],

       [[-1.0744787 , -0.27898353,  0.77826726, ..., -0.26323825,
         -0.51106733, -0.6095979 ],
        [-1.0681347 , -0.28388745,  0.77888167, ..., -0.26668283,
         -0.50530535, -0.6156523 ],
        [-1.066542  , -0.28799742,  0.77952117, ..., -0.26415208,
         -0.5053626 , -0.6203433 ],
        ...,
        [-0.9565688 , -0.42344972,  0.74836737, ..., -0.30987775,
         -0.48972553, -0.6779521 ],
        [-0.95612174, -0.4202316 ,  0.7563185 , ..., -0.31078815,
         -0.48975015, -0.6860772 ],
        [-0.95369875, -0.4140351 ,  0.75551313, ..., -0.3086175 ,
         -0.483304  , -0.6965898 ]],

       [[-1.0820639 , -0.29101023,  0.39918813, ..., -0.23768768,
         -1.0465809 , -0.6168238 ],
        [-1.0753988 , -0.2973768 ,  0.40242705, ..., -0.2370702 ,
         -1.0470564 , -0.62836313],
        [-1.0772306 , -0.30899942,  0.40505797, ..., -0.23441617,
         -1.0481813 , -0.62885   ],
        ...,
        [-0.92022794, -0.44941002,  0.684904  , ..., -0.44193476,
         -0.70990115, -0.73695415],
        [-0.92046714, -0.44672006,  0.6923772 , ..., -0.4436846 ,
         -0.7120436 , -0.7452704 ],
        [-0.9176997 , -0.44449446,  0.6924351 , ..., -0.4432382 ,
         -0.70576406, -0.7558112 ]],

       ...,

       [[-1.1151699 , -0.27326325,  0.344872  , ..., -0.18431245,
         -0.9981333 , -0.5878479 ],
        [-1.1085954 , -0.2804821 ,  0.34827134, ..., -0.18191433,
         -0.9992156 , -0.59706914],
        [-1.1101906 , -0.28786424,  0.35241288, ..., -0.17925419,
         -1.0010451 , -0.6001679 ],
        ...,
        [-0.9385589 , -0.44062847,  0.6574066 , ..., -0.4073303 ,
         -0.6778204 , -0.7141561 ],
        [-0.93889254, -0.43809134,  0.66541564, ..., -0.40946472,
         -0.67937356, -0.72202045],
        [-0.93675834, -0.43555105,  0.66596955, ..., -0.40904197,
         -0.67261803, -0.73233604]],

       [[-0.66200435, -0.5438706 ,  0.41360998, ..., -0.5734119 ,
         -1.2951593 , -0.8138643 ],
        [-0.6504916 , -0.5483213 ,  0.41255218, ..., -0.57450116,
         -1.297404  , -0.8185586 ],
        [-0.648916  , -0.5608711 ,  0.40843153, ..., -0.5728477 ,
         -1.2980266 , -0.818958  ],
        ...,
        [-0.6424503 , -0.58519363,  0.7060744 , ..., -0.6918927 ,
         -0.8618091 , -0.95516694],
        [-0.64402163, -0.5830415 ,  0.71310973, ..., -0.6926694 ,
         -0.86141396, -0.9628229 ],
        [-0.6427464 , -0.5778872 ,  0.7142331 , ..., -0.6931855 ,
         -0.854031  , -0.9713798 ]],

       [[-1.11488   , -0.1606243 ,  0.76729363, ..., -0.3525351 ,
         -0.27754867, -0.628352  ],
        [-1.1124992 , -0.1657942 ,  0.7672269 , ..., -0.3527527 ,
         -0.27550083, -0.64121103],
        [-1.116444  , -0.1725991 ,  0.77099574, ..., -0.35226142,
         -0.26988044, -0.6406872 ],
        ...,
        [-0.94410723, -0.3953225 ,  0.71756005, ..., -0.4460932 ,
         -0.3247249 , -0.6992749 ],
        [-0.9456006 , -0.390841  ,  0.7233339 , ..., -0.44671166,
         -0.32394528, -0.7076318 ],
        [-0.94342035, -0.38204324,  0.7211661 , ..., -0.44460556,
         -0.3171408 , -0.71704674]]], dtype=float32)>, <tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
array([[[-0.5729613 , -0.5550019 ,  0.7042439 , ..., -0.50745445,
         -1.340574  , -0.77086926],
        [-0.5667232 , -0.5601543 ,  0.70482457, ..., -0.5096249 ,
         -1.3380775 , -0.77475154],
        [-0.56656057, -0.56546825,  0.7015346 , ..., -0.5068848 ,
         -1.3372638 , -0.77578485],
        ...,
        [-0.60477597, -0.5858737 ,  0.7949227 , ..., -0.72856784,
         -0.82987696, -0.9535187 ],
        [-0.60559756, -0.583377  ,  0.8027031 , ..., -0.7300835 ,
         -0.8297913 , -0.96148014],
        [-0.6022334 , -0.5784957 ,  0.80438435, ..., -0.7305188 ,
         -0.82397777, -0.96943325]],

       [[-1.0738926 , -0.28261757,  0.77548003, ..., -0.26844493,
         -0.5269834 , -0.6142976 ],
        [-1.0662366 , -0.2872608 ,  0.77681434, ..., -0.2709448 ,
         -0.5209994 , -0.6217147 ],
        [-1.0666413 , -0.2905241 ,  0.7761999 , ..., -0.26778007,
         -0.5216739 , -0.624984  ],
        ...,
        [-0.95717025, -0.4270342 ,  0.7449168 , ..., -0.31357545,
         -0.50645345, -0.68220705],
        [-0.95628566, -0.42390278,  0.7524953 , ..., -0.31446248,
         -0.50622714, -0.6907257 ],
        [-0.9534703 , -0.4178499 ,  0.7512862 , ..., -0.31231567,
         -0.49943596, -0.7013802 ]],

       [[-1.0846065 , -0.29519922,  0.39243606, ..., -0.23633611,
         -1.0399027 , -0.6204077 ],
        [-1.0776411 , -0.3030645 ,  0.39485547, ..., -0.23693427,
         -1.040965  , -0.6311804 ],
        [-1.0783868 , -0.31231168,  0.3990058 , ..., -0.23357207,
         -1.041502  , -0.63420767],
        ...,
        [-0.92163795, -0.45179525,  0.680697  , ..., -0.44249436,
         -0.7053234 , -0.73901266],
        [-0.9218228 , -0.44918296,  0.6884368 , ..., -0.44419703,
         -0.70716774, -0.7472601 ],
        [-0.9189216 , -0.44737202,  0.6886496 , ..., -0.4439164 ,
         -0.7008352 , -0.757876  ]],

       ...,

       [[-1.1086454 , -0.27162546,  0.34467083, ..., -0.19708861,
         -1.0057219 , -0.5925371 ],
        [-1.0998476 , -0.27846527,  0.3461043 , ..., -0.19442016,
         -1.0068274 , -0.60296524],
        [-1.1040218 , -0.28340414,  0.35132122, ..., -0.19089402,
         -1.0066004 , -0.6058751 ],
        ...,
        [-0.93698055, -0.4381225 ,  0.65499085, ..., -0.41326603,
         -0.68250793, -0.7167329 ],
        [-0.9372965 , -0.43539536,  0.6627072 , ..., -0.41542545,
         -0.68410826, -0.7247571 ],
        [-0.9351757 , -0.43284246,  0.66333956, ..., -0.41494665,
         -0.67733675, -0.73522043]],

       [[-0.652085  , -0.5539138 ,  0.39845446, ..., -0.57609683,
         -1.3091455 , -0.8160727 ],
        [-0.64180464, -0.55835205,  0.39686382, ..., -0.57705855,
         -1.3118187 , -0.8218053 ],
        [-0.6370058 , -0.5728572 ,  0.39419925, ..., -0.5765649 ,
         -1.311376  , -0.82021046],
        ...,
        [-0.6379863 , -0.5876891 ,  0.7020473 , ..., -0.69053996,
         -0.8690919 , -0.95529956],
        [-0.6394373 , -0.5853572 ,  0.7091211 , ..., -0.69147116,
         -0.8689954 , -0.9633396 ],
        [-0.63779736, -0.580183  ,  0.71042585, ..., -0.69189185,
         -0.861884  , -0.97254914]],

       [[-1.0886846 , -0.1846832 ,  0.7908901 , ..., -0.3901965 ,
         -0.31872588, -0.6570971 ],
        [-1.0864179 , -0.18873072,  0.79249406, ..., -0.39156643,
         -0.31610084, -0.6675334 ],
        [-1.0881407 , -0.19720088,  0.7952812 , ..., -0.38922486,
         -0.3134062 , -0.67080307],
        ...,
        [-0.9236978 , -0.41613284,  0.7360109 , ..., -0.47380295,
         -0.36279324, -0.72523767],
        [-0.92527163, -0.41112754,  0.74216795, ..., -0.47532642,
         -0.36145592, -0.73378474],
        [-0.92235386, -0.40307236,  0.7408001 , ..., -0.47411853,
         -0.3552125 , -0.74272907]]], dtype=float32)>]

Arguments received by CrossMultiHeadAttention.call():
  • x=['tf.Tensor(shape=(32, 200, 128), dtype=float32)', 'tf.Tensor(shape=(32, 200, 128), dtype=float32)', 'tf.Tensor(shape=(32, 200, 128), dtype=float32)']
  • y=tf.Tensor(shape=(32, 200, 128), dtype=float32)
  • mask=tf.Tensor(shape=(32, 1, 200, 200), dtype=float32)

In [ ]:
input=[encoder_out, batch[1], decoder_self_attention_mask, decoder_cross_attention_mask]
a,b,c,d=input

In [ ]:
b.shape,type(b)

In [ ]:
aa=np.char.decode(np.array(batch[1][0]),"utf-8")
print(aa)
print(type(aa))
print(aa.shape)
aa=aa[np.newaxis,...]
f=[p for p in list(aa)]
ss=[p for p in f[0]]
ss

In [46]:
class Decoder(tf.keras.layers.Layer):
    def __init__(self,d_model,num_heads,dff,num_decoders,max_sequence_length,language_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN):
        super().__init__()
        self.num_decoders=num_decoders
        self.sentence_embedding=SentenceEmbedding(max_sequence_length=max_sequence_length, d_model=d_model, language_to_index=language_to_index, START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
        self.layers=SequentialDecoder([Decoder_layer(d_model=d_model,num_heads=num_heads,dff=dff) for _ in range(num_decoders)])
    def call(self,x,y,self_attention_mask,cross_attention_mask,start_token,end_token):
        y=self.sentence_embedding(x=y,start_token=start_token,end_token=end_token)
        y=self.layers(x,y,self_attention_mask,cross_attention_mask)
        return y

In [47]:
dec=Decoder(d_model=d_model,num_heads=num_heads,dff=512,num_decoders=12,max_sequence_length=english_max_length,language_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
dec

<Decoder name=decoder, built=False>

In [48]:
decoder_out=[]
i=0
for inputs, targets in ex_dataset.as_numpy_iterator():
    q=dec(encoder_out[i],targets,self_attention_mask=decoder_self_attention_mask,cross_attention_mask=decoder_cross_attention_mask,start_token=True,end_token=True)
    decoder_out.append(q)
    i=i+1

shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)


In [49]:
decoder_out

[<tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
 array([[[-0.12675643, -1.236485  ,  0.83896685, ...,  0.9615514 ,
          -1.0675697 ,  0.6910839 ],
         [ 0.25561354, -1.4587431 ,  1.5860904 , ...,  0.85845864,
          -1.1830355 ,  0.9274713 ],
         [ 0.22521988, -2.118495  ,  1.7130054 , ...,  0.8661974 ,
          -1.3735244 ,  1.215216  ],
         ...,
         [ 0.69056064, -1.6265372 ,  1.7750108 , ...,  0.3218359 ,
          -0.32397062,  0.7509952 ],
         [ 0.08341514, -1.9896104 ,  1.8339286 , ...,  0.41262177,
          -0.23586677,  0.599564  ],
         [-0.52436805, -1.6517448 ,  1.4073623 , ...,  0.50126094,
          -0.19646999,  0.5848802 ]],
 
        [[ 0.06443958, -1.2698898 ,  0.55010194, ...,  0.8248065 ,
          -0.88962567,  0.19901723],
         [ 0.42031652, -1.4723619 ,  1.2789083 , ...,  0.8127414 ,
          -1.0535455 ,  0.48613787],
         [ 0.43921334, -2.1460023 ,  1.4687192 , ...,  0.728765  ,
          -1.2868421 ,  0.7

In [50]:
class Transformer(tf.keras.Model):
    def __init__(self,d_model,num_heads,dff,num_layers,target_vocab_size,max_sequence_length,english_to_index,telugu_to_index,START_TOKEN,END_TOKEN,PADDING_TOKEN):
        super().__init__()
        self.encoder=Encoder(d_model=d_model,num_heads=num_heads,dff=dff,num_encoders=num_layers,max_sequence_length=max_sequence_length,language_to_index=english_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
        self.decoder=Decoder(d_model=d_model,num_heads=num_heads,dff=dff,num_decoders=num_layers,max_sequence_length=max_sequence_length,language_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
        self.final_layer=tf.keras.layers.Dense(target_vocab_size)
    def call(self,input,output,encoder_padding_mask,decoder_self_attention_mask,decoder_cross_attention_mask,enc_start_token,enc_end_token,dec_start_token,dec_end_token):
        input=self.encoder(x=input,mask=encoder_padding_mask,start_token=enc_start_token,end_token=enc_end_token)
        decoder_out=self.decoder(x=input,y=output,self_attention_mask=decoder_self_attention_mask,cross_attention_mask=decoder_self_attention_mask,start_token=dec_start_token,end_token=dec_end_token)
        out=self.final_layer(decoder_out)
        return out
        

In [51]:
transformer1=Transformer(d_model=d_model,num_heads=8,dff=512,num_layers=8,target_vocab_size=len(telugu_vocabulary),max_sequence_length=200,english_to_index=english_to_index,telugu_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
transformer1

<Transformer name=transformer, built=False>

In [52]:
transformer1_out=[]
for inputs, targets in ex_dataset.as_numpy_iterator():
    encoder_self_attention_mask,decoder_self_attention_mask,decoder_cross_attention_mask=create_masks(inputs,targets,max_sequence_length)
    out=transformer1(input=inputs,output=targets,encoder_padding_mask=encoder_self_attention_mask,decoder_self_attention_mask=decoder_self_attention_mask,decoder_cross_attention_mask=decoder_cross_attention_mask,enc_start_token=True,enc_end_token=True,dec_start_token=True,dec_end_token=True)
    transformer1_out.append(out)

shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)
shape of x= (32,)


In [53]:
transformer1_out

[<tf.Tensor: shape=(32, 200, 200), dtype=float32, numpy=
 array([[[-0.9805976 ,  0.26144007, -0.44898546, ..., -0.16023135,
          -0.28240028,  0.21092094],
         [-0.96884197,  0.48624775, -0.7030204 , ...,  0.02565575,
          -0.34626055,  0.3026498 ],
         [-0.8836389 ,  0.62890166, -1.0194259 , ...,  0.22547042,
          -0.41912046,  0.4871763 ],
         ...,
         [-1.1965665 ,  0.9623729 , -0.35888073, ...,  1.0347722 ,
          -0.99591994, -0.52045894],
         [-1.1215929 ,  0.9340674 , -0.36325344, ...,  0.83151424,
          -0.8709799 , -0.46235687],
         [-1.0077833 ,  0.75008017, -0.34515855, ...,  0.5804842 ,
          -0.6513667 , -0.45095974]],
 
        [[-0.9834087 ,  0.2401881 , -0.4326916 , ..., -0.13490653,
          -0.27415076,  0.15732469],
         [-0.9563782 ,  0.500438  , -0.6833268 , ...,  0.05365911,
          -0.43095502,  0.26959205],
         [-0.9102559 ,  0.596536  , -0.94664   , ...,  0.2711814 ,
          -0.48502964,  0.4

In [66]:
len(telugu_vocabulary)

200

In [67]:
transformer1.trainable_variables

[<KerasVariable shape=(71, 128), dtype=float32, path=transformer/encoder_2/sentence_embedding_2/embedding_2/embeddings>,
 <KerasVariable shape=(128, 128), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer_24/multi_head_attention_36/dense_264/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer_24/multi_head_attention_36/dense_264/bias>,
 <KerasVariable shape=(128, 128), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer_24/multi_head_attention_36/dense_265/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer_24/multi_head_attention_36/dense_265/bias>,
 <KerasVariable shape=(128, 128), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer_24/multi_head_attention_36/dense_266/kernel>,
 <KerasVariable shape=(128,), dtype=float32, path=transformer/encoder_2/sequential_encoder_2/encoder_layer

In [68]:
len(transformer1.trainable_variables)

324

In [54]:
def prediction(out):
    probabilities = tf.nn.softmax(out, axis=-1)  # Shape: (batch_size, sequence_length, vocab_size)

# Step 2: Get the most likely character ID for each position
    predicted_ids = tf.argmax(probabilities, axis=-1)  # Shape: (batch_size, sequence_length)

# Step 3: Convert predicted character IDs to their respective characters
    predicted_chars = np.vectorize(index_to_telugu.get)(predicted_ids.numpy())  # Maps the ID to the corresponding character

# Step 4: Combine characters into full strings for each sequence
    predicted_sentences = [''.join(sentence) for sentence in predicted_chars]

# Output the predicted sentences
#for i, sentence in enumerate(predicted_sentences):
 #   print(f"Predicted sentence {i+1}: {sentence}")

In [55]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')

def loss_function(real, pred):
    # real: (batch_size, seq_len)
    # pred: (batch_size, seq_len, vocab_size)
    mask = tf.math.logical_not(tf.math.equal(real, 0))  # Masking padding tokens
    loss_ = loss_object(real, pred)

    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask  # Apply the mask to the loss

    return tf.reduce_sum(loss_) / tf.reduce_sum(mask)  # Normalize loss by number of non-masked tokens


In [60]:
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):
    def __init__(self, d_model, warmup_steps=4000):
        super(CustomSchedule, self).__init__()

        self.d_model = d_model
        self.d_model = tf.cast(self.d_model, tf.float32)
        self.warmup_steps = warmup_steps

    def __call__(self, step):
        step = tf.cast(step, tf.float32)
        arg1 = tf.math.rsqrt(step)
        arg2 = step * (self.warmup_steps ** -1.5)

        return tf.math.rsqrt(self.d_model) * tf.math.minimum(arg1, arg2)

learning_rate = CustomSchedule(d_model=512)
optimizer = tf.keras.optimizers.Adam(learning_rate, beta_1=0.9, beta_2=0.98, epsilon=1e-9)


In [57]:
def create_padding_mask(seq):
    seq = tf.cast(tf.math.equal(seq, 0), tf.float32)
    return seq[:, tf.newaxis, tf.newaxis, :]  # Add extra dimensions to fit attention shape

def create_look_ahead_mask(size):
    mask = 1 - tf.linalg.band_part(tf.ones((size, size)), -1, 0)
    return mask  # Mask out future tokens


In [58]:

def train_step(transformer, inputs, targets, encoder_self_attention_mask,decoder_self_attention_mask , ncoder_cross_attention_mask):
    # inputs: input sequence to the encoder
    # targets: output sequence to the decoder (shifted by 1 for teacher forcing)
    
    #target_input = targets[:, :-1]  # Remove the last token
    #target_real = targets[:, 1:]    # Shifted by one to the right
   
    
    #with tf.compat.v1.Session() as sess:
       # p=sess.run(targets)
    with tf.GradientTape() as tape:
        def get_numpy_array(tensor):
            return tensor.numpy()
       
         # Forward pass through the transformer
        predictions = transformer(input=inputs,output=targets,encoder_padding_mask=encoder_self_attention_mask,decoder_self_attention_mask=decoder_self_attention_mask,decoder_cross_attention_mask=decoder_cross_attention_mask,enc_start_token=True,enc_end_token=True,dec_start_token=True,dec_end_token=True)
        t= transformer.decoder.sentence_embedding.decoding(np.array(targets))
        targets= transformer.decoder.sentence_embedding.batch_tokenize(t, start_token=False, end_token=True)
       
        # Calculate the loss
        loss = loss_function(targets, predictions)

    # Compute gradients
    gradients = tape.gradient(loss, transformer.trainable_variables)

    # Update weights using the optimizer
    optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))

    return loss


In [ ]:
EPOCHS = 5

for epoch in range(EPOCHS):
    total_loss = 0
     # Create the masks
        #enc_padding_mask = create_padding_mask(inputs)
        #dec_padding_mask = create_padding_mask(targets)
        #look_ahead_mask = create_look_ahead_mask(tf.shape(targets)[1])
        #combined_mask = tf.maximum(dec_padding_mask, look_ahead_mask)
        
    for inputs, targets in ex_dataset.as_numpy_iterator():
       
        encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask=create_masks(np.array(inputs),np.array(targets),max_sequence_length=200)
        # Run a single training step
        loss = train_step(transformer1, inputs, targets, encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask)
        
        total_loss += loss

    print(f'Epoch {epoch+1}, Loss: {total_loss / num_batches}')


shape of x= (32,)
shape of x= (32,)


In [151]:
for inputs, targets in ex_dataset.as_numpy_iterator():
    encoder_self_attention_mask,decoder_self_attention_mask,decoder_cross_attention_mask=create_masks(inputs,targets,max_sequence_length)
    predictions = transformer1(input=inputs,output=targets,encoder_padding_mask=encoder_self_attention_mask,decoder_self_attention_mask=decoder_self_attention_mask,decoder_cross_attention_mask=decoder_cross_attention_mask,enc_start_token=True,enc_end_token=True,dec_start_token=True,dec_end_token=True)
    print(inputs.shape)  

    
#inputs=np.array(inputs)
#for idx in range(len(inputs)):
s#=len(inputs[idx])
type(inputs)

shape of x= (32,)
shape of x= (32,)
(32,)
shape of x= (32,)
shape of x= (32,)
(32,)
shape of x= (32,)
shape of x= (32,)
(32,)


numpy.ndarray

In [152]:
j=0
for i in targets:
    print(i.decode("utf-8"))
    j=j+1
print(j)
type(i) 

ఈ దాడిలోనే దాదాపు 300 మంది ముష్కరులు ప్రాణాలు వదిలారు.
ఈ సమస్య ప్రత్యేక శ్రద్ధ అవసరం.
రింత రెచ్చిపోయారు.
మనం తనకోసం చేసేవాటిని యెహోవా ఎలా చూస్తాడు?
గతంలో చోటు చేసుకున్నకొన్ని సంఘటనలు .
న్యూఢిల్లీ: గుజరాత్ కేడర్ ఐపీఎస్ ఆఫీసర్ రాకేశ్ ఆస్థానాను బోర్డర్ సెక్యూరిటీ ఫోర్స్ (బీఎస్ఎఫ్) డైరెక్టర్ జనరల్గా కేంద్రం నియమించింది.
వెంకట్ రామ్జీ ఈ చిత్రం ద్వారా దర్శకుడిగా పరిచయమవుతున్నారు.
ఇరు పక్షాల మధ్య తీవ్రస్థాయిలో వాదోపవాదాలు సాగాయి.
కొత్త చలాన్లు వస్తూనే ఉన్నాయి.
ఈ ఘటనలన్నింటిపై పోలీసులు క్షుణ్ణంగా విచారణ జరపనున్నారు.
రైతుల నోట్లో మట్టికొడుతున్న ప్రభుత్వం
సడెన్గా ఎందుకిలా?
ఇక ప్రపంచ జనాభా మొత్తంగా అడ్డూ అదుపూ లేకుండా పెరిగిపోతోంది.
చిరుత సంచరించిన దృశ్యాలు సీసీ కెమెరాల్లో రియార్డయ్యాయి.
పార్లమెంట్ స్థానం
 -, పెన్పాయింట్  లేదా పెన్ విండోస్ను అమలు చేస్తున్న 3125 మోడల్ పెన్ కంప్యూటర్ను విడుదల చేసింది.
దీంతో రెపో రేటు 6 శాతానికి దిగివచ్చింది.
ఈ అద్భుతమైన రాత్రి ఆనందించండి!
జార్ఖండ్కు మైనింగ్ ఎంత ప్రాధాన్యత కలిగినదో వివరిస్తూ శ్రీ జోషి, జార్ఖండ్కు మైనింగ్ జీవన రేఖ వంటిందని, జార్ఖండ్ అభివృద్ధిలో ఇది క

bytes

In [ ]:
 for batch, (inputs, targets) in enumerate(dataset):
    continue
    #target_input = targets[:, :-1]  # Remove the last token
    #target_real = targets[:, 1:] 
targets[:5]

In [ ]:
def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, PADDING_TOKEN))
    loss_ = loss_object(real, pred)
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    return tf.reduce_sum(loss_) / tf.reduce_sum(mask)


def train_step(eng_batch, tel_batch, transformer, optimizer):
    with tf.GradientTape() as tape:
        encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask = create_masks(eng_batch, tel_batch,max_sequence_length=200)

        tel_predictions = transformer(
            eng_batch,
            tel_batch,
            encoder_self_attention_mask,
            decoder_self_attention_mask,
            decoder_cross_attention_mask,
            enc_start_token=False,
            enc_end_token=False,
            dec_start_token=True,
            dec_end_token=True
        )
        k= transformer.decoder.sentence_embedding.decoding(np.array(tel_batch))
        labels = transformer.decoder.sentence_embedding.batch_tokenize(k, start_token=False, end_token=True)
        #loss = loss_function(labels, tel_predictions)
    
    #gradients = tape.gradient(loss, transformer.trainable_variables)
    #optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))

    return tel_predictions,labels

In [ ]:
labels=[]
tel_predictions=[]
optimizer = tf.keras.optimizers.Adam()
for eng_batch, tel_batch in ex_dataset.as_numpy_iterator():
    a,b= train_step(eng_batch,tel_batch,transformer1,optimizer)
    labels.append(b)
    tel_predictions.append(a)

In [ ]:
labels[2].shape,tel_predictions[2].shape

In [ ]:
with tf.GradientTape() as tape:
    """predictions = transformer1(eng_batch,
            tel_batch,
            encoder_self_attention_mask,
            decoder_self_attention_mask,
            decoder_cross_attention_mask,
            enc_start_token=False,
            enc_end_token=False,
            dec_start_token=True,
            dec_end_token=True)  # Model's forward pass"""
    loss = loss_function(labels[0],tel_predictions[0] )  # Loss calculation
#gradients = tape.gradient(loss, transformer1.trainable_variables)
#len(gradients)
loss

In [ ]:
for layer in transformer1.trainable_variables:
    print(f"Layer {layer.name} is trainable: {layer.trainable}")


In [ ]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam()
with tf.GradientTape() as tape:
    #output = transformer1(input_data)
    loss = loss_function(labels[2],tel_predictions[2])

gradients = tape.gradient(loss, transformer1.trainable_variables)

# Debug the gradients
for grad, var in zip(gradients, transformer1.trainable_variables):
    if grad is None:
        print(f"No gradient for {var.name}")
    else:
        print(f"Gradient for {var.name}: {grad.shape}")


In [ ]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam()
with tf.GradientTape() as tape:
    #output = transformer1(input_data)  # shape [32, 200, 200]
    loss = loss_function(labels[2],tel_predictions[2])  # true_labels shape [32, 200]

print(f"Loss: {loss}")
gradients = tape.gradient(loss, transformer1.trainable_variables)
#optimizer.apply_gradients(zip(gradients, transformer1.trainable_variables))
for grad, var in zip(gradients, transformer1.trainable_variables):
    if grad is None:
        print(f"Warning: No gradient computed for variable {var.name}")
    else:
        print(f"Gradient computed for {var.name}: {grad.shape}")

# Filter out None gradients and apply the rest
gradients_vars = [(grad, var) for grad, var in zip(gradients, transformer1.trainable_variables) if grad is not None]

if gradients_vars:
    optimizer.apply_gradients(gradients_vars)
else:
    print("No valid gradients to apply.")

In [ ]:
"""loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')
for i,j in zip(tel_predictions,labels):
    with tf.GradientTape() as tape:
        loss = loss_function(j, i)
        gradients = tape.gradient(loss, transformer1.trainable_variables)
        optimizer.apply_gradients(zip(gradients, transformer1.trainable_variables))"""
with tf.GradientTape() as tape:
    gradients = tape.gradient(loss, transformer1.trainable_variables)
    print(gradients)


In [ ]:
with tf.GradientTape() as tape:
    #tape.watch(transformer1.trainable_variables)  # Optional, but helps with debugging
    #predictions = transformer1(inputs)
    loss = loss_function(labels[2],tel_predictions[2])


In [ ]:
loss.shape

In [ ]:
for var in transformer1.trainable_variables:
    print(var.name, var.shape)


In [ ]:
transformer2=Transformer(d_model=d_model,num_heads=8,dff=512,num_layers=8,target_vocab_size=len(telugu_vocabulary),max_sequence_length=200,english_to_index=english_to_index,telugu_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
transformer

In [ ]:
transformer2.summary()

In [ ]:
def masked_loss(label, pred):
  mask = label != 0
  loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')
  loss = loss_object(label, pred)

  mask = tf.cast(mask, dtype=loss.dtype)
  loss *= mask

  loss = tf.reduce_sum(loss)/tf.reduce_sum(mask)
  return loss


def masked_accuracy(label, pred):
  pred = tf.argmax(pred, axis=2)
  label = tf.cast(label, pred.dtype)
  match = label == pred

  mask = label != 0

  match = match & mask

  match = tf.cast(match, dtype=tf.float32)
  mask = tf.cast(mask, dtype=tf.float32)
  return tf.reduce_sum(match)/tf.reduce_sum(mask)


In [ ]:
optimizer = tf.keras.optimizers.Adam()

In [ ]:
transformer2.compile(
    loss=masked_loss,
    optimizer=optimizer,
    metrics=[masked_accuracy])

In [ ]:
transformer2.fit([input=eng,output=tel,encoder_padding_mask=encoder_self_attention_mask,decoder_self_attention_mask=decoder_self_attention_mask,decoder_cross_attention_mask=decoder_cross_attention_mask,enc_start_token=True,enc_end_token=True,dec_start_token=True,dec_end_token=True]

                epochs=20,
                )

In [ ]:

"""# Optimizer and loss function setup
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')

# Custom loss function that ignores padding tokens
def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, PADDING_TOKEN))
    loss_ = loss_object(real, pred)
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    return tf.reduce_sum(loss_) / tf.reduce_sum(mask)

# Training step for a single batch
@tf.function
def train_step(eng_batch, tel_batch, transformer, optimizer):
    with tf.GradientTape() as tape:
        encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask = create_masks(eng_batch, tel_batch,max_sequence_length=200)

        tel_predictions = transformer(
            eng_batch,
            tel_batch,
            encoder_self_attention_mask,
            decoder_self_attention_mask,
            decoder_cross_attention_mask,
            enc_start_token=False,
            enc_end_token=False,
            dec_start_token=True,
            dec_end_token=True
        )

        labels = transformer.decoder.sentence_embedding.batch_tokenize(tel_batch, start_token=False, end_token=True)
        loss = loss_function(labels, tel_predictions)
    
    gradients = tape.gradient(loss, transformer.trainable_variables)
    optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))

    return loss

# Custom train function to loop over the dataset
def train_model(transformer, train_dataset, num_epochs):
    for epoch in range(num_epochs):
        print(f'Epoch {epoch + 1}')
        total_loss = 0
        batch_num=0

        for eng_batch, tel_batch in train_dataset.as_numpy_iterator():
            loss = train_step(eng_batch, tel_batch, transformer, optimizer)
            total_loss += loss

            if batch_num % 100 == 0:
                print(f'Batch {batch_num}: Loss {loss.numpy()}')
                # Additional logging for debugging purposes
                predicted_sentence = evaluate_sentence(transformer, eng_batch[0])
                print(f'Predicted translation: {predicted_sentence}')
            batch_num=batch_num+1
        print(f'Epoch {epoch + 1}, Loss: {total_loss.numpy()}')

# Evaluation step (inference) for translating a sentence
def evaluate_sentence(transformer, eng_sentence):
    tel_sentence = ['']
    for word_counter in range(max_sequence_length):
        encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask = create_masks(eng_sentence, tel_sentence,max_sequence_length=200)
        
        predictions = transformer(
            eng_sentence,
            tel_sentence,
            encoder_self_attention_mask,
            decoder_self_attention_mask,
            decoder_cross_attention_mask,
            enc_start_token=False,
            enc_end_token=False,
            dec_start_token=True,
            dec_end_token=False
        )

        next_token_prob_distribution = predictions[0, -1, :]
        next_token_index = tf.argmax(next_token_prob_distribution, axis=-1).numpy()

        next_token = index_to_telugu[next_token_index]
        tel_sentence.append(next_token)

        if next_token == END_TOKEN:
            break

    return ' '.join(kn_sentence)

# Model training
num_epochs = 10
train_model(transformer2,ex_dataset, num_epochs)"""



In [ ]:
"""for eng_batch, tel_batch in ex_dataset.as_numpy_iterator():
    encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask = create_masks(eng_batch, tel_batch,max_sequence_length=200)
encoder_self_attention_mask"""                                                                   

In [ ]:
transformer3=Transformer(d_model=d_model,num_heads=8,dff=512,num_layers=8,target_vocab_size=len(telugu_vocabulary),max_sequence_length=200,english_to_index=english_to_index,telugu_to_index=telugu_to_index,START_TOKEN=START_TOKEN,END_TOKEN=END_TOKEN,PADDING_TOKEN=PADDING_TOKEN)
transformer3

In [ ]:


# Define loss function (sparse categorical crossentropy for token prediction)
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')

# Define the optimizer (Adam is commonly used for transformers)
optimizer = tf.keras.optimizers.Adam()

# Function to calculate loss
def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, PADDING_TOKEN))  # Ignore padding tokens
    loss_ = loss_object(real, pred)
    
    # Apply the mask to zero out the loss for padding tokens
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask

    return tf.reduce_sum(loss_) / tf.reduce_sum(mask)

# Backpropagation function for a single batch
@tf.function
def train_step(eng_batch, tel_batch, transformer, optimizer):
    with tf.GradientTape() as tape:
        # Create masks for the batch
        encoder_self_attention_mask, decoder_self_attention_mask, decoder_cross_attention_mask = create_masks(
            eng_batch, tel_batch, max_sequence_length=200
        )
        
        # Forward pass: Get predictions from transformer
        tel_predictions = transformer(
            eng_batch,
            tel_batch,
            encoder_self_attention_mask,
            decoder_self_attention_mask,
            decoder_cross_attention_mask,
            enc_start_token=False,
            enc_end_token=False,
            dec_start_token=True,
            dec_end_token=True
        )
        
        # Labels: Target Telugu sentence (shifted by one token)
        labels = tel_batch
        
        # Compute the loss
        loss = loss_function(labels, tel_predictions)
    
    # Backward pass: Calculate gradients
    gradients = tape.gradient(loss, transformer.trainable_variables)
    
    # Update the model's weights
    optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))
    
    return loss

# Training loop
def train_model(transformer, dataset, num_epochs):
    for epoch in range(num_epochs):
        print(f'Epoch {epoch + 1}/{num_epochs}')
        total_loss = 0
        
        # Iterate over each batch in the dataset
        for (batch_num, (eng_batch, tel_batch)) in enumerate(dataset):
            # Perform backpropagation on each batch
            batch_loss = train_step(eng_batch, tel_batch, transformer, optimizer)
            total_loss += batch_loss
            
            if batch_num % 100 == 0:
                print(f'Batch {batch_num} Loss {batch_loss:.4f}')
        
        print(f'Epoch {epoch + 1} Loss: {total_loss/len(dataset):.4f}')


In [ ]:
train_model(transformer3,ex_dataset,3)