In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [3]:
START_TOKEN="<start>"
END_TOKEN="<end>"
PADDING_TOKEN="<pad>"
telugu_vocabulary = [
     START_TOKEN, ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', 
    '3', '4', '5', '6', '7', '8', '9', ':', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`',
    "అ", "ఆ", "ఇ", "ఈ", "ఉ", "ఊ", "ఋ", "ఌ", "ఎ", "ఏ", "ఐ", "ఒ", "ఓ", "ఔ", "క", "ఖ", "గ", "ఘ", "ఙ", 
    "చ", "ఛ", "జ", "ఝ", "ఞ", "ట", "ఠ", "డ", "ఢ", "ణ", "త", "థ", "ద", "ధ", "న", "ప", "ఫ", "బ", "భ", "మ", 
    "య", "ర", "ఱ", "ల", "ళ", "ఴ", "వ", "శ", "ష", "స", "హ", "ౠ", "◌ా", "◌ి", "◌ీ", "ు", "ూ", "ృ", "ౄ", 
    "◌ె", "◌ే", "◌ై", "◌ొ", "◌ో", "◌ౌ", "◌ౢ", "◌ౣ", ".", "।", "॥", "॰", "◌్", "◌ౕ", "◌ౖ", "◌ఀ", "ఁ",  'ా','ి',
'ీ','ె','ే','ై','ొ','ో', 'ౌ','్','ౖ','౦','౧','౨','౩','౭','౯','ಂ','ಆ','ಕ','ಗ','ಚ','ಜ','ನ','ಬ','ಮ','ರ','ಳ','ಾ','ಿ','ು','ೂ','ೆ','್','ງ','ດ','ທ','ປ','ມ','ລ','ວ','ອ','ະ','າ','ື','ເ','–','—','‘','’','“','”','‡','•','․','…', '′','″',
   
'آ',
 'ئ',
 'ا',
 'ب',
 'ة',
 'ت',
 'د',
 'ر',
 'ز',
 'ش',
 'ض',
 'ع',
 'ف',
 'ق',
 'ل',
 'و',
 'پ',
 'ہ',
 'ی',
 'ं',"ం", "ః", "ॐ", '{', '|', '}', '~' , PADDING_TOKEN, END_TOKEN
]
english_vocabulary = [
    START_TOKEN, ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', 
    '3', '4', '5', '6', '7', '8', '9', ':', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c',
    'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 
    'z', '{', '|', '}', '~', PADDING_TOKEN, END_TOKEN
]


In [4]:
telugu_vocabulary=set(telugu_vocabulary)
    

In [5]:

with open("C:/Users/nchar/Desktop/eng-to-tel_translation/train_en.txt", 'r',encoding="utf-8") as file:
    english_sentences = file.readlines()
with open("C:/Users/nchar/Desktop/eng-to-tel_translation/train_te.txt", 'r',encoding="utf_8") as file:
    telugu_sentences = file.readlines()

english_sentences

['Rise again.\n',
 'How do we glorify Jehovahs undeserved kindness?\n',
 'India also continues to push back economically.\n',
 'I remember my childhood days.\n',
 'All transactions are made online.\n',
 'I love night shoots in my city.\n',
 'Three members of a family were killed in the incident.\n',
 'The film is directed by V V Vinayak.\n',
 'The Hyderabad weather office forecast more rains.\n',
 'We are family!\n',
 'In this context, the Rs.\n',
 'What is the phrase?\n',
 'In Monaco-Ville, street signs are printed in both French and Mongasque.\n',
 'The same has been confirmed in a report carried by BBC.\n',
 "I said, 'who are you?'\n",
 'In this state they can easily survive one year or longer.\n',
 'The complete details of his death are yet to be known.\n',
 'If You Go...\n',
 '"All the very best."""\n',
 'What is this, child?\n',
 'Speaking during another Session on Reducing poverty through social and economic transformation, Shri Gangwar the Government of India, under the leaders

In [6]:
index_to_telugu = {k:v for k,v in enumerate(telugu_vocabulary)}
telugu_to_index = {v:k for k,v in enumerate(telugu_vocabulary)}
index_to_english = {k:v for k,v in enumerate(english_vocabulary)}
english_to_index = {v:k for k,v in enumerate(english_vocabulary)}

In [7]:
l=[]
for k in index_to_telugu.keys():
    l.append(k)
len(l)

200

In [8]:
telugu_to_index[PADDING_TOKEN]

15

In [9]:
PERCENTILE = 97
print( f"{PERCENTILE}th percentile length telugu: {np.percentile([len(x) for x in telugu_sentences], PERCENTILE)}" )
print( f"{PERCENTILE}th percentile length English: {np.percentile([len(x) for x in english_sentences], PERCENTILE)}" )

97th percentile length telugu: 169.0
97th percentile length English: 177.0


In [10]:
TOTAL_SENTENCES = 10000
english_sentences = english_sentences[:TOTAL_SENTENCES]
telugu_sentences = telugu_sentences[:TOTAL_SENTENCES]
english_sentences = [sentence.rstrip('\n').lower() for sentence in english_sentences]
telugu_sentences = [sentence.rstrip('\n') for sentence in telugu_sentences]
     

telugu_sentences[:10]

['మళ్లీ ఉదయిస్తాడు.',
 'యెహోవా కృపను మనమెలా మహిమపరచవచ్చు?',
 'ఆర్థికంగా కూడా భారత్\u200c వే గంగా పయనిస్తున్నది.',
 '‘విద్యార్థులను చూస్తుంటే నాకు చిన్నప్పటి రోజులు గుర్తుకొస్తున్నాయి.',
 'ఆర్థిక లావాదేవీలన్నీ ఆన్\u200cలైన్\u200cలోనే',
 'పద్మినీ స్త్రీ రాత్రి వేళల్లో రతికి ఇష్టపడదు.',
 'ఓకే కుటుంబానికి చెందిన ముగ్గురు మృతిచెందటంతో ఈ సంఘటన కలవరపర్చింది.',
 'ఆ సినిమాకు వి. వి. వినాయక్\u200c దర్శకత్వం వహించనున్నారు.',
 'హైదరాబాద్\u200cకు మరో భారీ వర్షం సూచనలున్నాయని వాతావరణ శాఖ హెచ్చరించింది.',
 'మనం అంటున్న మమ్ముట్టి ఫ్యామిలీ !']

In [11]:
# Replace specific unwanted characters
telugu_sentences = [sentence.replace('\u200B', '').replace('\u200C', '').replace('\u200D', '') for sentence in telugu_sentences]


In [12]:
max_sequence_length = 200

def is_valid_tokens(sentence, vocab):
    l=set()
    for token in list(set(sentence)):
        if token not in vocab:
            l.add(token)
    return l

def is_valid_length(sentence, max_sequence_length):
    return len(list(sentence)) < (max_sequence_length - 1) # need to re-add the end token so leaving 1 space


p=set()
for index in range(len(telugu_sentences)):
    telugu_sentence, english_sentence = telugu_sentences[index], english_sentences[index]
    a=is_valid_tokens(telugu_sentence, telugu_vocabulary)
    for i in a:
        p.add(i)


In [13]:
index=[]
for i in range(len(telugu_sentences)):
    if( is_valid_length(telugu_sentences[i],200)and is_valid_length(english_sentences[i],200)):
        index.append(i)

        
        
       


    
    

In [14]:
telugu_sentences = [telugu_sentences[i] for i in index]
english_sentences = [english_sentences[i] for i in index]

In [15]:
len(telugu_sentences)

9776

In [16]:
len(english_sentences)

9776

In [17]:
s=[]
for sentence in telugu_sentences:
    b=sentence
    for a in p:
        if a in b:
            b=b.replace(a,"")
    s.append(b)
len(s)

9776

In [18]:
telugu_cleaned_sentences=s
telugu_cleaned_sentences[:10]

['మళ్లీ ఉదయిస్తాడు.',
 'యెహోవా కృపను మనమెలా మహిమపరచవచ్చు?',
 'ఆర్థికంగా కూడా భారత్ వే గంగా పయనిస్తున్నది.',
 '‘విద్యార్థులను చూస్తుంటే నాకు చిన్నప్పటి రోజులు గుర్తుకొస్తున్నాయి.',
 'ఆర్థిక లావాదేవీలన్నీ ఆన్లైన్లోనే',
 'పద్మినీ స్త్రీ రాత్రి వేళల్లో రతికి ఇష్టపడదు.',
 'ఓకే కుటుంబానికి చెందిన ముగ్గురు మృతిచెందటంతో ఈ సంఘటన కలవరపర్చింది.',
 'ఆ సినిమాకు వి. వి. వినాయక్ దర్శకత్వం వహించనున్నారు.',
 'హైదరాబాద్కు మరో భారీ వర్షం సూచనలున్నాయని వాతావరణ శాఖ హెచ్చరించింది.',
 'మనం అంటున్న మమ్ముట్టి ఫ్యామిలీ !']

In [19]:
len(telugu_cleaned_sentences)

9776

In [20]:

class TextDataset:

    def __init__(self, english_sentences, telugu_cleaned_sentences):
        self.english_sentences = english_sentences
        self.telugu_sentences = telugu_cleaned_sentences

    def __len__(self):
        return len(self.english_sentences)

    def __getitem__(self, idx):
        return self.english_sentences[idx], self.telugu_sentences[idx]

    def to_tf_dataset(self, batch_size=32, shuffle=True):
        # Create a TensorFlow dataset from the sentence pairs
        dataset = tf.data.Dataset.from_tensor_slices((self.english_sentences, self.telugu_sentences))
        
        if shuffle:
            dataset = dataset.shuffle(buffer_size=len(self.english_sentences))

        # Batch the dataset
        dataset = dataset.batch(batch_size)

        # Prefetch to improve performance
        dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

        return dataset


In [21]:
dataset = TextDataset(english_sentences,telugu_cleaned_sentences)

In [22]:
batch_size=32
tf_dataset = dataset.to_tf_dataset(batch_size=batch_size)

In [23]:
len(tf_dataset)

306

In [24]:
ex_dataset=tf_dataset.take(13)

In [25]:
# Create an iterator
iterator = iter(ex_dataset.as_numpy_iterator())

# Fetch the next batch
batch = next(iterator)
batch

(array([b'directed by raj kiran, the films music has been scored by praveen lakkaraju.',
        b'could not believe.',
        b'it symbolizes the heart that they had to face their enemies.',
        b'conventional crts are well under 1 ms, and plasma and oled displays boast times on the order of 0.001 ms.',
        b'the phone runs the mediatek helio p22 processor.',
        b'the sumerians used slaves, although they were not a major part of the economy.',
        b'i dont want to go.', b'see the recipe on youtube.',
        b'petrol price hike', b'why do black holes exist?',
        b'wobbly start', b'what is the need to do all of this?',
        b'pm modi invited for inauguration of new bjp office',
        b'girls did not go to schools because of lack of toilets.',
        b'"those guilty should be handed out stringent punished."""',
        b'for example, compare two chapters of revelation.',
        b'warangal district congress president naini rajender reddy',
        b'it is po

In [26]:
english_max_len=200
telugu_max_len=200
d_model=128
class SentenceEmbedding(tf.keras.layers.Layer):
    "For a given sentence, create an embedding"
    def __init__(self, max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.max_sequence_length = max_sequence_length
        self.embedding = tf.keras.layers.Embedding(self.vocab_size, d_model)
        self.language_to_index = language_to_index
        #self.position_encoder = PositionalEncoding(d_model, max_sequence_length)
        #self.dropout = nn.Dropout(p=0.1)
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.PADDING_TOKEN = PADDING_TOKEN
    
    def batch_tokenize(self, batch, start_token, end_token):

        def tokenize(sentence, start_token, end_token):
            sentence_word_indicies = [self.language_to_index[token] for token in list(sentence)]
            if start_token:
                sentence_word_indicies.insert(0, self.language_to_index[self.START_TOKEN])
            if end_token:
                sentence_word_indicies.append(self.language_to_index[self.END_TOKEN])
            for _ in range(len(sentence_word_indicies), self.max_sequence_length):
                sentence_word_indicies.append(self.language_to_index[self.PADDING_TOKEN])
            return tf.convert_to_tensor(sentence_word_indicies)

        tokenized = []
        for sentence_num in range(len(batch)):
           tokenized.append( tokenize(batch[sentence_num], start_token, end_token) )
        tokenized = tf.stack(tokenized)
        return tokenized
    
    def call(self, x, start_token, end_token): # sentence
        x = self.batch_tokenize(x, start_token, end_token)
        #x = self.embedding(x)
        #pos = self.position_encoder().to(get_device())
        #x = self.dropout(x + pos)
        return x

In [27]:
s=SentenceEmbedding(max_sequence_length=english_max_len, d_model=d_model, language_to_index=english_to_index, START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
"""for batch_num, batch in enumerate(iterator):
        eng_batch, kn_batch = batch"""
        
        

'for batch_num, batch in enumerate(iterator):\n        eng_batch, kn_batch = batch'

In [28]:
for element in ex_dataset.as_numpy_iterator():
    eng_list=element[0]
    tel_list=element[1]
    decoded_tel_list=[]
    decoded_eng_list=[]
    for i,j in zip(tel_list,eng_list):
        p=np.char.decode(i,"utf-8")
        p=p.tolist()
        decoded_tel_list.append(p)
        q=np.char.decode(j,"utf-8")
        q=q.tolist()
        decoded_eng_list.append(q)
        
    #k=s(eng_list,start_token=False,end_token=False)
type(eng_list)

numpy.ndarray

In [29]:
decoded_tel_list

['ప్రపంచంలోని అతి పెద్ద బొగ్గు ఉత్పత్తి సంస్థ సీఐఎల్, భారత్లో విద్యుత్ రంగానికి పొడి ఇంధనాన్ని సరఫరా చేసే ప్రధాన సంస్థ.',
 'ఏం మాట్లాడినా !',
 'దీంతో పోలీసులు నలుగురిపై కేసు నమోదు చేశారు.',
 'ఇండియన్ ట్రేడ్ ప్రమోషన్ ఆర్గనైజేషన్(ఐటిపిఒ), సహాకారంతో నేషనల్ బుక్ ట్రస్ట్(ఎన్బిటి) నిర్వహించిన ఈ బుక్ ఫెయిర్ ప్రగతి మైదానంలో జరగనుంది.',
 'ప్రతి సంవత్సరం ఈ వేడకలు మద్రాసులో వారం నుంచి నెల రోజుల పాటు జరుగుతాయి.',
 '‘వదిన(చిన్నీ) ఎప్పటికీ అలాంటి పని చేయదు’ అంటాడు.',
 'ప్రతి వారి సొంత ప్రత్యేకతలు కలిగి.',
 'పార్లమెంటు ఎన్నికల తర్వాత తెలంగాణలో బీజేపీ అనూహ్యంగా పుంజుకుంది.',
 'లక్ష కోట్ల వృక్షార్చన!',
 '""" అన్నాడు ఒకడు."',
 'వీరిలో చిన్నారులు కూడా ఉన్నారు.',
 'దళితుల అభ్యున్నతికి పాటుపడిన వ్యక్తి అంబేద్కర్ అన్నారు.',
 'కానీ సినిమా అంటే కొన్ని దృశ్యాలు మాత్రమే కాదు కదా.',
 'ఇప్పటికే టికెట్స్ మొత్తం అయిపోయాయి.',
 'అయితే, అతను విఫలమయ్యాడు.',
 'మందారం ఆకులు:',
 'శారీరక వ్యాయామాలు.',
 'ఇలాంటి కేసులు చాలా చాలా అరుదు.',
 'పండుగెక్కడ!',
 'ఈ ఘటనకు సంబంధించి అప్పట్లో పలు కేసులు నమోదయ్యాయి.',
 'ఈ తరుణంలో రాష్ట్

In [30]:
def tokenize(sentence, start_token, end_token,language_to_index,max_sequence_length):
    print(sentence)
    sentence_word_indicies= [language_to_index.get(token, '<UNK>') for token in list(sentence)]
    print(sentence_word_indicies)
    if start_token:
        sentence_word_indicies.insert(0,language_to_index[START_TOKEN])
    if end_token:
        sentence_word_indicies.append(language_to_index[END_TOKEN])
    for _ in range(len(sentence_word_indicies), max_sequence_length):
        sentence_word_indicies.append(language_to_index[PADDING_TOKEN])
    return sentence_word_indicies
z=tokenize(decoded_eng_list[0],start_token=False, end_token=False,language_to_index=english_to_index,max_sequence_length=english_max_len)

cil, the world''s largest coal producing company, is a major supplier of the dry fuel to the power sector in india.
[41, 47, 50, 13, 1, 58, 46, 43, 1, 61, 53, 56, 50, 42, 8, 8, 57, 1, 50, 39, 56, 45, 43, 57, 58, 1, 41, 53, 39, 50, 1, 54, 56, 53, 42, 59, 41, 47, 52, 45, 1, 41, 53, 51, 54, 39, 52, 63, 13, 1, 47, 57, 1, 39, 1, 51, 39, 48, 53, 56, 1, 57, 59, 54, 54, 50, 47, 43, 56, 1, 53, 44, 1, 58, 46, 43, 1, 42, 56, 63, 1, 44, 59, 43, 50, 1, 58, 53, 1, 58, 46, 43, 1, 54, 53, 61, 43, 56, 1, 57, 43, 41, 58, 53, 56, 1, 47, 52, 1, 47, 52, 42, 47, 39, 15]


In [31]:
print(z)
len(z)

[41, 47, 50, 13, 1, 58, 46, 43, 1, 61, 53, 56, 50, 42, 8, 8, 57, 1, 50, 39, 56, 45, 43, 57, 58, 1, 41, 53, 39, 50, 1, 54, 56, 53, 42, 59, 41, 47, 52, 45, 1, 41, 53, 51, 54, 39, 52, 63, 13, 1, 47, 57, 1, 39, 1, 51, 39, 48, 53, 56, 1, 57, 59, 54, 54, 50, 47, 43, 56, 1, 53, 44, 1, 58, 46, 43, 1, 42, 56, 63, 1, 44, 59, 43, 50, 1, 58, 53, 1, 58, 46, 43, 1, 54, 53, 61, 43, 56, 1, 57, 43, 41, 58, 53, 56, 1, 47, 52, 1, 47, 52, 42, 47, 39, 15, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69]


200

In [32]:
index_to_english[69]

'<pad>'

In [33]:
aa=decoded_eng_list[0]
print(aa)
len(aa)

cil, the world''s largest coal producing company, is a major supplier of the dry fuel to the power sector in india.


115

In [34]:
i=0
for token in list(aa):
    print(token)
    i=i+1
i

c
i
l
,
 
t
h
e
 
w
o
r
l
d
'
'
s
 
l
a
r
g
e
s
t
 
c
o
a
l
 
p
r
o
d
u
c
i
n
g
 
c
o
m
p
a
n
y
,
 
i
s
 
a
 
m
a
j
o
r
 
s
u
p
p
l
i
e
r
 
o
f
 
t
h
e
 
d
r
y
 
f
u
e
l
 
t
o
 
t
h
e
 
p
o
w
e
r
 
s
e
c
t
o
r
 
i
n
 
i
n
d
i
a
.


115

In [35]:
def decode_text_dataset(dataset):
    a=[]
    out=[]
    for batch in dataset:
        text = batch[1]  
        # Assuming the first element in the tuple is the text field
        for i in text:
                a=out
                #i=np.array(i)
                p=i.numpy().decode('UTF-8')
                out.append(p)

    return out
    

#decode_text(tf_dataset)
# Apply the function to the dataset
#decoded_dataset = tf_dataset.map(decode_text)


In [36]:
def batch_tokenize( batch, start_token, end_token,language_to_index,max_sequence_length):
    def tokenize(sentence, start_token, end_token,language_to_index,max_sequence_length):
         sentence_word_indicies= [language_to_index.get(token, '<UNK>') for token in list(sentence)]
         if start_token:
            sentence_word_indicies.insert(0, language_to_index[START_TOKEN])
         if end_token:
            sentence_word_indicies.append(language_to_index[END_TOKEN])
         for _ in range(len(sentence_word_indicies), max_sequence_length):
            sentence_word_indicies.append(language_to_index[PADDING_TOKEN])
         return tf.convert_to_tensor(sentence_word_indicies)

    tokenized = []
    for sentence_num in range(len(batch)):
        tokenized.append( tokenize(batch[sentence_num], start_token, end_token,language_to_index,max_sequence_length) )
    tokenized=tf.convert_to_tensor(tokenized)
    return tokenized
    

In [37]:
len(decoded_eng_list),len(decoded_eng_list[0])

(32, 115)

In [38]:
s=batch_tokenize(batch=decoded_eng_list, start_token=True, end_token=True,language_to_index=english_to_index,max_sequence_length=english_max_len)

In [39]:
s

<tf.Tensor: shape=(32, 200), dtype=int32, numpy=
array([[ 0, 41, 47, ..., 69, 69, 69],
       [ 0, 61, 46, ..., 69, 69, 69],
       [ 0, 58, 46, ..., 69, 69, 69],
       ...,
       [ 0, 51, 39, ..., 69, 69, 69],
       [ 0, 40, 59, ..., 69, 69, 69],
       [ 0, 59, 52, ..., 69, 69, 69]])>

In [40]:
decoded_tel_list

['ప్రపంచంలోని అతి పెద్ద బొగ్గు ఉత్పత్తి సంస్థ సీఐఎల్, భారత్లో విద్యుత్ రంగానికి పొడి ఇంధనాన్ని సరఫరా చేసే ప్రధాన సంస్థ.',
 'ఏం మాట్లాడినా !',
 'దీంతో పోలీసులు నలుగురిపై కేసు నమోదు చేశారు.',
 'ఇండియన్ ట్రేడ్ ప్రమోషన్ ఆర్గనైజేషన్(ఐటిపిఒ), సహాకారంతో నేషనల్ బుక్ ట్రస్ట్(ఎన్బిటి) నిర్వహించిన ఈ బుక్ ఫెయిర్ ప్రగతి మైదానంలో జరగనుంది.',
 'ప్రతి సంవత్సరం ఈ వేడకలు మద్రాసులో వారం నుంచి నెల రోజుల పాటు జరుగుతాయి.',
 '‘వదిన(చిన్నీ) ఎప్పటికీ అలాంటి పని చేయదు’ అంటాడు.',
 'ప్రతి వారి సొంత ప్రత్యేకతలు కలిగి.',
 'పార్లమెంటు ఎన్నికల తర్వాత తెలంగాణలో బీజేపీ అనూహ్యంగా పుంజుకుంది.',
 'లక్ష కోట్ల వృక్షార్చన!',
 '""" అన్నాడు ఒకడు."',
 'వీరిలో చిన్నారులు కూడా ఉన్నారు.',
 'దళితుల అభ్యున్నతికి పాటుపడిన వ్యక్తి అంబేద్కర్ అన్నారు.',
 'కానీ సినిమా అంటే కొన్ని దృశ్యాలు మాత్రమే కాదు కదా.',
 'ఇప్పటికే టికెట్స్ మొత్తం అయిపోయాయి.',
 'అయితే, అతను విఫలమయ్యాడు.',
 'మందారం ఆకులు:',
 'శారీరక వ్యాయామాలు.',
 'ఇలాంటి కేసులు చాలా చాలా అరుదు.',
 'పండుగెక్కడ!',
 'ఈ ఘటనకు సంబంధించి అప్పట్లో పలు కేసులు నమోదయ్యాయి.',
 'ఈ తరుణంలో రాష్ట్

In [41]:
p=batch_tokenize(batch=decoded_tel_list, start_token=True, end_token=True,language_to_index=telugu_to_index,max_sequence_length=telugu_max_len)
p

<tf.Tensor: shape=(32, 200), dtype=int32, numpy=
array([[173,  28,  30, ...,  15,  15,  15],
       [173,  21,  96, ...,  15,  15,  15],
       [173, 189, 114, ...,  15,  15,  15],
       ...,
       [173,  63,  85, ...,  15,  15,  15],
       [173,   5, 119, ...,  15,  15,  15],
       [173,   5, 119, ...,  15,  15,  15]])>

In [42]:
class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self,d_model,sequence_length):
        super().__init__()
        self.d_model=d_model
        self.seq_len=sequence_length
    def call(self):
        even_i=np.arange(0,self.d_model,2,dtype="float32")
        even_denominator=10000**(2*(even_i/self.d_model))
        odd_i=np.arange(1,self.d_model,2,dtype="float32")
        odd_denominator=10000**(2*(odd_i/self.d_model))
        position=np.arange(0,self.seq_len,dtype="float32")
        position=np.reshape(self.seq_len,(self.seq_len,1))
        sin_values=np.sin(position/even_denominator)
        cos_values=np.cos(position/odd_denominator)
        final=np.zeros((self.seq_len,self.d_model),dtype="float32")
        final[:,0::2]=final[:,0::2]+sin_values
        final[:,1::2]=final[:,1::2]+cos_values
        return final

In [43]:

class SentenceEmbedding(tf.keras.layers.Layer):
    "For a given sentence, create an embedding"
    def __init__(self, max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.max_sequence_length = max_sequence_length
        self.embedding = tf.keras.layers.Embedding(self.vocab_size, d_model)
        self.language_to_index = language_to_index
        self.d_model=d_model
        #self.position_encoder = PositionalEncoding(d_model, max_sequence_length)
        self.dropout = tf.keras.layers.Dropout(rate=0.1)
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.PADDING_TOKEN = PADDING_TOKEN
    def decoding(self,batch):
        decoded_list=[]
        for i in (batch):
            p=np.char.decode(i,"utf-8")
            p=p.tolist()
            decoded_list.append(p)
        return decoded_list
    def position_encoder(self):
        # Create the positional encodings with shape (max_sequence_length, d_model)
        pos = np.arange(self.max_sequence_length)[:, np.newaxis]
        i = np.arange(self.d_model)[np.newaxis, :]
        
        # Positional encoding formula used in Transformer models
        angle_rads = pos / np.power(10000, (2 * (i // 2)) / np.float32(self.d_model))
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])  # Apply sin to even indices
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])  # Apply cos to odd indices
        
        pos_encoding = angle_rads[np.newaxis, ...]  # Add batch dimension
        return tf.cast(pos_encoding, dtype=tf.float32)
    def batch_tokenize(self, batch, start_token, end_token):
        
        OOV_TOKEN = self.language_to_index.get("<unk>", self.vocab_size - 1)
        def tokenize(sentence, start_token, end_token):
            
            sentence_word_indicies = [self.language_to_index.get(token, OOV_TOKEN) for token in list(sentence)]
            if start_token:
                sentence_word_indicies.insert(0, self.language_to_index[self.START_TOKEN])
            if end_token:
                sentence_word_indicies.append(self.language_to_index[self.END_TOKEN])
            for _ in range(len(sentence_word_indicies), self.max_sequence_length):
                sentence_word_indicies.append(self.language_to_index[self.PADDING_TOKEN])
            return tf.convert_to_tensor(sentence_word_indicies)

        tokenized = []
        for sentence_num in range(len(batch)):
           tokenized.append( tokenize(batch[sentence_num], start_token, end_token) )
        tokenized = tf.stack(tokenized)
        return tokenized
    
    def call(self, x, start_token, end_token): # sentence
        x=self.decoding(np.array(x))
        x = self.batch_tokenize(x, start_token, end_token)
        x = self.embedding(x)
        pos = self.position_encoder()
        x = self.dropout(x + pos)
        return x

In [44]:
w=SentenceEmbedding(d_model=d_model,language_to_index=english_to_index,max_sequence_length=english_max_len,START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
eng,tel=batch
v=w(x=eng,start_token=True, end_token=True,)

In [62]:
np.char.decode(batch[0][0])

array('directed by raj kiran, the films music has been scored by praveen lakkaraju.',
      dtype='<U76')

In [46]:
w=SentenceEmbedding(d_model=d_model,language_to_index=telugu_to_index,max_sequence_length=telugu_max_len,START_TOKEN=START_TOKEN, END_TOKEN=END_TOKEN, PADDING_TOKEN=PADDING_TOKEN)
eng,tel=batch
v=w(x=tel,start_token=True, end_token=True,)

In [47]:
v

<tf.Tensor: shape=(32, 200, 128), dtype=float32, numpy=
array([[[-0.03925762,  1.0370177 , -0.04047717, ...,  1.0000066 ,
          0.03045211,  1.0169547 ],
        [ 0.814781  ,  0.54474676,  0.7604996 , ...,  0.95133305,
         -0.032285  ,  1.0146515 ],
        [ 0.914107  , -0.42346743,  0.94638187, ...,  0.98996145,
          0.03356431,  1.0398532 ],
        ...,
        [ 0.7956598 , -0.65298414,  0.8287733 , ...,  0.96162874,
          0.00413216,  1.0334932 ],
        [-0.07972468, -1.044261  ,  0.98630476, ...,  0.9616252 ,
          0.00424761,  1.0334905 ],
        [-0.88194495, -0.51905805,  0.46052957, ...,  0.9616217 ,
          0.00436306,  1.0334879 ]],

       [[-0.03925762,  1.0370177 , -0.04047717, ...,  1.0000066 ,
          0.03045211,  1.0169547 ],
        [ 0.8829156 ,  0.5670801 ,  0.775999  , ...,  1.0453001 ,
          0.04156152,  0.9996056 ],
        [ 0.958374  , -0.436179  ,  0.99581057, ...,  1.0455911 ,
          0.02792239,  1.0261549 ],
        ...

In [48]:
 for i in tel:
    p=np.char.decode(i,"utf-8")
    p=p.tolist()
    decoded_tel_list.append(p)
decoded_tel_list[20]

'ఈ తరుణంలో రాష్ట్ర ప్రభుత్వం కీలక నిర్ణయం తీసుకుంది.'

In [49]:
telugu_to_index[index_to_telugu[tel[20][81]]]

KeyError: 224

In [ ]:
 decoded_eng_list=[]
eng,tel=batch
print(type(tel))
print(tel.shape)
for i in (tel):
    p=np.char.decode(i,"utf-8")
    p=p.tolist()
    decoded_eng_list.append(p)
decoded_eng_list