In [1]:
import numpy as np
import tensorflow as tf

In [2]:
from math import sqrt
import pandas as pd

In [3]:
data=pd.read_csv("C:/Users/nchar/Desktop/english_to_french_translator/eng_-french.csv")
df=pd.DataFrame(data)
print(df.info())
df.dropna(axis=0,inplace=True)
inp=df["English words/sentences"][0:1000]
inp=list(inp)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175621 entries, 0 to 175620
Data columns (total 2 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   English words/sentences  175621 non-null  object
 1   French words/sentences   175621 non-null  object
dtypes: object(2)
memory usage: 2.7+ MB
None


In [4]:
inp=[(word.split()) for word in inp]

In [5]:
inp

[['Hi.'],
 ['Run!'],
 ['Run!'],
 ['Who?'],
 ['Wow!'],
 ['Fire!'],
 ['Help!'],
 ['Jump.'],
 ['Stop!'],
 ['Stop!'],
 ['Stop!'],
 ['Wait!'],
 ['Wait!'],
 ['Go', 'on.'],
 ['Go', 'on.'],
 ['Go', 'on.'],
 ['Hello!'],
 ['Hello!'],
 ['I', 'see.'],
 ['I', 'try.'],
 ['I', 'won!'],
 ['I', 'won!'],
 ['I', 'won.'],
 ['Oh', 'no!'],
 ['Attack!'],
 ['Attack!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Cheers!'],
 ['Get', 'up.'],
 ['Go', 'now.'],
 ['Go', 'now.'],
 ['Go', 'now.'],
 ['Got', 'it!'],
 ['Got', 'it!'],
 ['Got', 'it?'],
 ['Got', 'it?'],
 ['Got', 'it?'],
 ['Hop', 'in.'],
 ['Hop', 'in.'],
 ['Hug', 'me.'],
 ['Hug', 'me.'],
 ['I', 'fell.'],
 ['I', 'fell.'],
 ['I', 'know.'],
 ['I', 'left.'],
 ['I', 'left.'],
 ['I', 'lied.'],
 ['I', 'lost.'],
 ['I', 'paid.'],
 ["I'm", '19.'],
 ["I'm", 'OK.'],
 ["I'm", 'OK.'],
 ['Listen.'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['No', 'way!'],
 ['Really?'],
 ['Real

In [6]:

t=tf.keras.preprocessing.text.Tokenizer()
t.fit_on_texts(inp)

In [7]:
inp_encds=t.texts_to_sequences(inp)
inp_encds

[[305],
 [183],
 [183],
 [306],
 [307],
 [184],
 [308],
 [309],
 [134],
 [134],
 [134],
 [185],
 [185],
 [6, 26],
 [6, 26],
 [6, 26],
 [186],
 [186],
 [1, 187],
 [1, 74],
 [1, 188],
 [1, 188],
 [1, 31],
 [135, 310],
 [189],
 [189],
 [103],
 [103],
 [103],
 [103],
 [9, 14],
 [6, 104],
 [6, 104],
 [6, 104],
 [40, 27],
 [40, 27],
 [40, 136],
 [40, 136],
 [40, 136],
 [190, 41],
 [190, 41],
 [137, 7],
 [137, 7],
 [1, 105],
 [1, 105],
 [1, 191],
 [1, 62],
 [1, 62],
 [1, 106],
 [1, 17],
 [1, 192],
 [2, 311],
 [2, 29],
 [2, 29],
 [312],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [42, 43],
 [138],
 [138],
 [138],
 [313],
 [5, 74],
 [5, 31],
 [5, 31],
 [5, 31],
 [5, 31],
 [139, 8],
 [314],
 [11, 37],
 [11, 37],
 [11, 37],
 [11, 140],
 [11, 44],
 [11, 44],
 [11, 44],
 [11, 44],
 [11, 44],
 [11, 44],
 [11, 315],
 [11, 75],
 [11, 75],
 [11, 75],
 [11, 75],
 [11, 75],
 [11, 75],
 [316, 3],
 [63, 7],
 [63, 7],
 [63, 32],
 [63, 32],
 [15, 41],
 [15, 41],
 

In [8]:

m=max([len(text) for text in inp_encds])
inp_encds=tf.keras.preprocessing.sequence.pad_sequences(inp_encds,padding="post",maxlen=10)
#inp_encds=tf.convert_to_tensor(inp_encds)
inp_encds.shape

(1000, 10)

In [9]:
inp_encds

array([[305,   0,   0, ...,   0,   0,   0],
       [183,   0,   0, ...,   0,   0,   0],
       [183,   0,   0, ...,   0,   0,   0],
       ...,
       [ 94, 304,   0, ...,   0,   0,   0],
       [164,  96,   0, ...,   0,   0,   0],
       [164, 112,   0, ...,   0,   0,   0]])

In [10]:
len(t.word_index)

465

In [11]:
embedding_dim=6
vocab_size=10000
embedding_layer=tf.keras.layers.Embedding(vocab_size,embedding_dim)
embedded_tokens=embedding_layer(inp_encds)
print(embedded_tokens.shape)

(1000, 10, 6)


In [12]:
embedded_tokens.shape #batch_size,seq_len,embedding_dimension  batch_size==>no of sequences in the batch

TensorShape([1000, 10, 6])

In [12]:
b=embedded_tokens[0]
b[np.newaxis,].shape

TensorShape([1, 10, 6])

In [13]:
num_heads=2
dim_head=embedding_dim//num_heads
dim_head

3

In [14]:
from tensorflow.keras.layers import Dense

"SelfAttention"

In [18]:
q=k=v=b

In [19]:
q.shape

TensorShape([10, 6])

In [20]:
dk=tf.shape(k)[-1]
dk=float(dk)
dk

6.0

In [21]:
np.set_printoptions(suppress=True)

In [22]:
qk=tf.matmul(q,k,transpose_b=True)
qk

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.00226133, -0.0015618 , -0.0015618 , -0.0015618 , -0.0015618 ,
        -0.0015618 , -0.0015618 , -0.0015618 , -0.0015618 , -0.0015618 ],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435368,
         0.00435368,  0.00435368,  0.00435368,  0.00435368,  0.00435368],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435368,
         0.00435368,  0.00435368,  0.00435368,  0.00435368,  0.00435368],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435368,
         0.00435368,  0.00435368,  0.00435368,  0.00435368,  0.00435368],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435368,
         0.00435368,  0.00435368,  0.00435368,  0.00435368,  0.00435368],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435368,
         0.00435368,  0.00435368,  0.00435368,  0.00435368,  0.00435368],
       [-0.0015618 ,  0.00435368,  0.00435368,  0.00435368,  0.00435

In [23]:
qk=qk/tf.math.sqrt(dk)
qk

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.00092318, -0.0006376 , -0.0006376 , -0.0006376 , -0.0006376 ,
        -0.0006376 , -0.0006376 , -0.0006376 , -0.0006376 , -0.0006376 ],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177738,
         0.00177738,  0.00177738,  0.00177738,  0.00177738,  0.00177738],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177738,
         0.00177738,  0.00177738,  0.00177738,  0.00177738,  0.00177738],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177738,
         0.00177738,  0.00177738,  0.00177738,  0.00177738,  0.00177738],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177738,
         0.00177738,  0.00177738,  0.00177738,  0.00177738,  0.00177738],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177738,
         0.00177738,  0.00177738,  0.00177738,  0.00177738,  0.00177738],
       [-0.0006376 ,  0.00177738,  0.00177738,  0.00177738,  0.00177

In [24]:
att=tf.nn.softmax(qk)
att

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.10014056, 0.09998439, 0.09998439, 0.09998439, 0.09998439,
        0.09998439, 0.09998439, 0.09998439, 0.09998439, 0.09998439],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10002413],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10002413],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10002413],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10002413],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10002413],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413, 0.10002413, 0.10002413, 0.10

In [25]:
out=tf.matmul(att,v)
out

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[-0.0072071 ,  0.02375522,  0.04189241,  0.00130873,  0.01489801,
         0.02591706],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745],
       [-0.00721594,  0.02377116,  0.04192053,  0.00130326,  0.01490764,
         0.02591745]], 

"MaskedSelfAttention"

In [26]:
mask=np.tril(np.ones((10,10)))
mask

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
mask[mask==0]=-np.infty
mask[mask==1]=0
mask

array([[  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [  0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [  0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [  0.,   0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf],
       [  0.,   0.,   0.,   0.,   0., -inf, -inf, -inf, -inf, -inf],
       [  0.,   0.,   0.,   0.,   0.,   0., -inf, -inf, -inf, -inf],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., -inf, -inf, -inf],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -inf, -inf],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [28]:
combined=att+mask
combined

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.10014056,       -inf,       -inf,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413,       -inf,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413, 0.10002413,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413,       -inf,       -inf,       -inf,       -inf],
       [0.09978286, 0.10002413, 0.10002413, 0.10002413, 0.10002413,
        0.10002413, 0.10002413,       -inf,       -inf,     

In [29]:
scores=tf.nn.softmax(combined)
scores

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.4999397 , 0.5000603 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.33327973, 0.33336014, 0.33336014, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.24995477, 0.25001508, 0.25001508, 0.25001508, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.19996141, 0.20000966, 0.20000966, 0.20000966, 0.20000966,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.16663316, 0.16667336, 0.16667336, 0.16667336, 0.16667336,
        0.16667336, 0.        , 0.        , 0.        , 0.        ],
       [0.1428276 , 0.14286207, 0.14286207, 0.14286207, 0.14286207,
        0.14286207, 0.14286207, 0.        , 0.        , 0.  

In [30]:
out=tf.matmul(scores,v)
out

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[ 0.01501756, -0.01634905, -0.02886399,  0.01505661, -0.00933175,
         0.02493191],
       [ 0.00266711,  0.00593727,  0.010456  ,  0.00741678,  0.00413295,
         0.02547937],
       [-0.00144905,  0.01336485,  0.02356056,  0.00487058,  0.00862047,
         0.02566183],
       [-0.003507  ,  0.01707841,  0.03011244,  0.00359756,  0.01086409,
         0.02575305],
       [-0.00474174,  0.01930648,  0.03404344,  0.00283377,  0.01221022,
         0.02580778],
       [-0.00556487,  0.02079183,  0.03666406,  0.00232459,  0.01310762,
         0.02584426],
       [-0.00615282,  0.02185278,  0.0385359 ,  0.00196089,  0.01374861,
         0.02587033],
       [-0.00659378,  0.02264848,  0.03993977,  0.00168812,  0.01422935,
         0.02588987],
       [-0.00693674,  0.02326736,  0.04103166,  0.00147597,  0.01460325,
         0.02590508],
       [-0.00721111,  0.02376246,  0.04190516,  0.00130625,  0.01490238,
         0.02591724]], 

"MultiHead"

In [31]:
b=tf.reshape(b,(1,10,6)) # (batch size,seqlen,embedding_dim)        batch_size==>no.of sequences in the batch
b.shape                   #seqlen==> no.of words in the sequences

TensorShape([1, 10, 6])

In [32]:
wq =tf.keras.layers.Dense(d_model)
wk =tf.keras.layers.Dense(d_model)
wv =tf.keras.layers.Dense(d_model)

In [33]:
q=wq(b)
k=wk(b)
v=wv(v)
q.shape

TensorShape([1, 10, 6])

In [34]:
seq_len=10
batch_size=1
num_heads=2
d_model=6
dim_head=int(d_model/num_heads)
dim_head

3

In [35]:
q=tf.reshape(q,(batch_size,seq_len,num_heads,dim_head))
k=tf.reshape(k,(batch_size,seq_len,num_heads,dim_head))
v=tf.reshape(v,(batch_size,seq_len,num_heads,dim_head))
q.shape

TensorShape([1, 10, 2, 3])

In [36]:
q=tf.transpose(q,perm=[0,2,1,3])
k=tf.transpose(k,perm=[0,2,1,3])
v=tf.transpose(v,perm=[0,2,1,3])
q.shape

TensorShape([1, 2, 10, 3])

"At first we reshape the q,k,v vectors by splitting the embedding dimension into num_heads*head_dim to give an equal no.of embedding dimension columns to each head and then we transpose the vector and push the seq_len and head_dim to last so that we can multiply with other vectors easily(the dimensions of each word in the sequence is multiplied with each dimension of the word in the sequence. this wil occur in each head and in each batch to give the vector of size (batch_size,num_heads,seq_len,seq_len))

In [37]:
a=tf.transpose(k,perm=[0,1,3,2])
a.shape

TensorShape([1, 2, 3, 10])

"here we transposed the k vector because when we multiply the k with q we transpose k in single with so that the shape of k will become (batch_size,embed_dim,seq_len) and the shape q is (batch_size,seq_len,embed_dim) and the result after multiplication will be (batch_size,seq_len,seq_len) that is the attention weight of each word w.r.t every word in that sequence/sentence but in multi-head instead of embed_dim we have head_dim so we transpose the seq_len and head_dim of k vector"

In [38]:
qk=tf.matmul(q,a)
qk.shape

TensorShape([1, 2, 10, 10])

"In above the multiplication of q and k occurs in each head which results the attention weights for each with total 10 words os the size is (batch_size,num_heads,seq_len,seq_len)"

In [39]:
dk=tf.shape(k)[-1]
dk=float(dk)
dk

3.0

In [40]:
qk=qk/tf.math.sqrt(dk)
qk

<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
array([[[[-0.00017162, -0.00053521, -0.00053521, -0.00053521,
          -0.00053521, -0.00053521, -0.00053521, -0.00053521,
          -0.00053521, -0.00053521],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,  0.00097879,  0.00097879,
           0.00

In [41]:
mask=np.tril(np.ones(qk.shape))
mask

array([[[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.,

In [42]:
mask[mask==0]=-np.infty
mask[mask==1]=0
mask

array([[[[  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0.,   0.,   0., -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0.,   0.,   0.,   0., -inf, -inf, -inf, -inf],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0., -inf, -inf, -inf],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -inf, -inf],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -inf],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]],

        [[  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [  0.,   0.,   0.,   0., -inf, -inf, -inf, -inf, -inf, -inf],
    

In [43]:
combined=qk+mask
combined

<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
array([[[[-0.00017162,        -inf,        -inf,        -inf,
                 -inf,        -inf,        -inf,        -inf,
                 -inf,        -inf],
         [ 0.00111798,  0.00097879,        -inf,        -inf,
                 -inf,        -inf,        -inf,        -inf,
                 -inf,        -inf],
         [ 0.00111798,  0.00097879,  0.00097879,        -inf,
                 -inf,        -inf,        -inf,        -inf,
                 -inf,        -inf],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
                 -inf,        -inf,        -inf,        -inf,
                 -inf,        -inf],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,        -inf,        -inf,        -inf,
                 -inf,        -inf],
         [ 0.00111798,  0.00097879,  0.00097879,  0.00097879,
           0.00097879,  0.00097879,        -inf,        -inf,
               

In [44]:
scores=tf.nn.softmax(combined)
scores

<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
array([[[[1.        , 0.        , 0.        , 0.        , 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ],
         [0.5000348 , 0.49996522, 0.        , 0.        , 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ],
         [0.33336428, 0.33331788, 0.33331788, 0.        , 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ],
         [0.2500261 , 0.24999131, 0.24999131, 0.24999131, 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ],
         [0.20002228, 0.19999444, 0.19999444, 0.19999444, 0.19999444,
          0.        , 0.        , 0.        , 0.        , 0.        ],
         [0.16668601, 0.16666281, 0.16666281, 0.16666281, 0.16666281,
          0.16666281, 0.        , 0.        , 0.        , 0.        ],
         [0.1428742 , 0.14285432, 0.14285432, 0.14285432, 0.14285432,
          0.14285432, 0.1428

In [45]:
out=tf.matmul(scores,v)
out

<tf.Tensor: shape=(1, 2, 10, 3), dtype=float32, numpy=
array([[[[ 0.00555862, -0.01201064, -0.03078554],
         [-0.02972335, -0.00079859, -0.02328196],
         [-0.0414851 ,  0.00293911, -0.02078054],
         [-0.04736618,  0.00480803, -0.01952978],
         [-0.05089489,  0.00592939, -0.01877932],
         [-0.0532474 ,  0.00667698, -0.018279  ],
         [-0.05492777,  0.00721098, -0.01792163],
         [-0.05618806,  0.00761148, -0.0176536 ],
         [-0.05716828,  0.00792298, -0.01744513],
         [-0.05795247,  0.00817218, -0.01727835]],

        [[ 0.01667558, -0.01768128, -0.02389509],
         [ 0.00613762, -0.00981358,  0.01340724],
         [ 0.00262476, -0.00719086,  0.02584206],
         [ 0.00086829, -0.00587947,  0.03205961],
         [-0.0001856 , -0.00509263,  0.03579019],
         [-0.0008882 , -0.00456806,  0.03827725],
         [-0.00139006, -0.00419337,  0.04005374],
         [-0.00176645, -0.00391235,  0.04138611],
         [-0.00205921, -0.00369378,  0.0424

In [46]:
out1=tf.transpose(out,perm=[0,2,1,3])
out1

<tf.Tensor: shape=(1, 10, 2, 3), dtype=float32, numpy=
array([[[[ 0.00555862, -0.01201064, -0.03078554],
         [ 0.01667558, -0.01768128, -0.02389509]],

        [[-0.02972335, -0.00079859, -0.02328196],
         [ 0.00613762, -0.00981358,  0.01340724]],

        [[-0.0414851 ,  0.00293911, -0.02078054],
         [ 0.00262476, -0.00719086,  0.02584206]],

        [[-0.04736618,  0.00480803, -0.01952978],
         [ 0.00086829, -0.00587947,  0.03205961]],

        [[-0.05089489,  0.00592939, -0.01877932],
         [-0.0001856 , -0.00509263,  0.03579019]],

        [[-0.0532474 ,  0.00667698, -0.018279  ],
         [-0.0008882 , -0.00456806,  0.03827725]],

        [[-0.05492777,  0.00721098, -0.01792163],
         [-0.00139006, -0.00419337,  0.04005374]],

        [[-0.05618806,  0.00761148, -0.0176536 ],
         [-0.00176645, -0.00391235,  0.04138611]],

        [[-0.05716828,  0.00792298, -0.01744513],
         [-0.00205921, -0.00369378,  0.04242239]],

        [[-0.05795247,  0.0

In [47]:
out2=tf.reshape(out1,(1,10,2*3))  #1=batch_size,10=seq_len , 2=num _heads , 3=dim_head , num_heads*dim_head=d_model
out2

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[ 0.00555862, -0.01201064, -0.03078554,  0.01667558,
         -0.01768128, -0.02389509],
        [-0.02972335, -0.00079859, -0.02328196,  0.00613762,
         -0.00981358,  0.01340724],
        [-0.0414851 ,  0.00293911, -0.02078054,  0.00262476,
         -0.00719086,  0.02584206],
        [-0.04736618,  0.00480803, -0.01952978,  0.00086829,
         -0.00587947,  0.03205961],
        [-0.05089489,  0.00592939, -0.01877932, -0.0001856 ,
         -0.00509263,  0.03579019],
        [-0.0532474 ,  0.00667698, -0.018279  , -0.0008882 ,
         -0.00456806,  0.03827725],
        [-0.05492777,  0.00721098, -0.01792163, -0.00139006,
         -0.00419337,  0.04005374],
        [-0.05618806,  0.00761148, -0.0176536 , -0.00176645,
         -0.00391235,  0.04138611],
        [-0.05716828,  0.00792298, -0.01744513, -0.00205921,
         -0.00369378,  0.04242239],
        [-0.05795247,  0.00817218, -0.01727835, -0.00229341,
         -0.00

In [48]:
linear=tf.keras.layers.Dense(d_model)

In [49]:
final_out=linear(out2)

In [50]:
final_out

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[-0.0199214 , -0.00875049,  0.00181175,  0.01826892,
          0.00781056,  0.02864456],
        [ 0.03406274,  0.0012218 ,  0.02320763,  0.02602022,
         -0.01496658,  0.00159727],
        [ 0.05205881,  0.00454618,  0.03034025,  0.02860425,
         -0.02255957, -0.00741928],
        [ 0.06105709,  0.00620842,  0.03390668,  0.02989632,
         -0.02635618, -0.01192771],
        [ 0.06645615,  0.00720578,  0.03604658,  0.03067158,
         -0.02863419, -0.01463281],
        [ 0.07005555,  0.00787069,  0.03747319,  0.03118843,
         -0.03015288, -0.01643623],
        [ 0.07262658,  0.00834564,  0.03849222,  0.0315576 ,
         -0.03123766, -0.0177244 ],
        [ 0.07455485,  0.00870185,  0.03925649,  0.03183449,
         -0.03205125, -0.01869053],
        [ 0.07605462,  0.0089789 ,  0.03985092,  0.03204984,
         -0.03268404, -0.01944197],
        [ 0.07725444,  0.00920054,  0.04032647,  0.03222213,
         -0.03

"NON MASKED MULTIHEAD"

In [51]:
non_masked_weights=tf.nn.softmax(qk)
non_masked_weights

<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
array([[[[0.10003273, 0.09999637, 0.09999637, 0.09999637, 0.09999637,
          0.09999637, 0.09999637, 0.09999637, 0.09999637, 0.09999637],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.09999862, 0.09999862, 0.09999862, 0.09999862],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.09999862, 0.09999862, 0.09999862, 0.09999862],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.09999862, 0.09999862, 0.09999862, 0.09999862],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.09999862, 0.09999862, 0.09999862, 0.09999862],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.09999862, 0.09999862, 0.09999862, 0.09999862],
         [0.10001253, 0.09999862, 0.09999862, 0.09999862, 0.09999862,
          0.09999862, 0.0999

In [52]:
non_masked_scores=tf.nn.softmax(non_masked_weights)
non_masked_scores

<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
array([[[[0.10000328, 0.09999964, 0.09999964, 0.09999964, 0.09999964,
          0.09999964, 0.09999964, 0.09999964, 0.09999964, 0.09999964],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.09999986, 0.09999986, 0.09999986, 0.09999986],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.09999986, 0.09999986, 0.09999986, 0.09999986],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.09999986, 0.09999986, 0.09999986, 0.09999986],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.09999986, 0.09999986, 0.09999986, 0.09999986],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.09999986, 0.09999986, 0.09999986, 0.09999986],
         [0.10000125, 0.09999986, 0.09999986, 0.09999986, 0.09999986,
          0.09999986, 0.0999

In [53]:
non_masked_out=tf.matmul(non_masked_scores,v)
non_masked_out

<tf.Tensor: shape=(1, 2, 10, 3), dtype=float32, numpy=
array([[[[-0.05795312,  0.00817239, -0.01727821],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818],
         [-0.05795326,  0.00817243, -0.01727818]],

        [[-0.00229348, -0.00351887,  0.04325169],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.04325195],
         [-0.00229356, -0.00351881,  0.0432

In [54]:
non_masked_out1=tf.transpose(non_masked_out,perm=[0,2,1,3])
non_masked_out1
                           

<tf.Tensor: shape=(1, 10, 2, 3), dtype=float32, numpy=
array([[[[-0.05795312,  0.00817239, -0.01727821],
         [-0.00229348, -0.00351887,  0.04325169]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.00817243, -0.01727818],
         [-0.00229356, -0.00351881,  0.04325195]],

        [[-0.05795326,  0.0

In [55]:
non_masked_final_out=tf.reshape(non_masked_out1,(1,10,2*3))
non_masked_final_out

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[-0.05795312,  0.00817239, -0.01727821, -0.00229348,
         -0.00351887,  0.04325169],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00351881,  0.04325195],
        [-0.05795326,  0.00817243, -0.01727818, -0.00229356,
         -0.00

In [56]:
la=Dense(d_model)

In [57]:
non_masked_final=la(non_masked_final_out)
non_masked_final

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[ 0.02878805, -0.03404238,  0.03508486,  0.02946632,
          0.04971742,  0.00658717],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04971766,  0.00658714],
        [ 0.02878815, -0.03404257,  0.03508497,  0.0294663 ,
          0.04

"POSITIONAL EMBEDDING"

In [60]:
seq_len=10
d_model=6

FORMULA
        P.E(POS,2i)=sin(pos/10000**(2i/d_model))  ==> for even
        P.E(POS,2i+1)=cos(pos/10000**(2i/d_model))  ==> for odd

    pos ==> position of word in sequence
    i  ==> dimensional index
    d_model ==> embedding length

In [61]:
even_i=np.arange(0,d_model,2,dtype="float32")
even_i

array([0., 2., 4.], dtype=float32)

In [62]:
even_denominator=10000**(2*(even_i/d_model))
even_denominator

array([     1.     ,    464.15897, 215443.55   ], dtype=float32)

In [63]:
odd_i=np.arange(1,d_model,2,dtype="float32")
odd_i

array([1., 3., 5.], dtype=float32)

In [64]:
odd_denominator=10000**(2*(odd_i/d_model))
odd_denominator

array([     21.54435,   10000.     , 4641587.     ], dtype=float32)

In [65]:
position=np.arange(0,seq_len,dtype="float32")
position=np.reshape(position,(seq_len,1))
position

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]], dtype=float32)

In [66]:
sin_values=np.sin(position/even_denominator)
sin_values

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.841471  ,  0.00215443,  0.00000464],
       [ 0.9092974 ,  0.00430886,  0.00000928],
       [ 0.14112   ,  0.00646326,  0.00001392],
       [-0.7568025 ,  0.00861763,  0.00001857],
       [-0.9589243 ,  0.01077196,  0.00002321],
       [-0.2794155 ,  0.01292625,  0.00002785],
       [ 0.6569866 ,  0.01508047,  0.00003249],
       [ 0.98935825,  0.01723462,  0.00003713],
       [ 0.41211846,  0.01938869,  0.00004177]], dtype=float32)

In [67]:
cos_values=np.cos(position/odd_denominator)
cos_values

array([[1.        , 1.        , 1.        ],
       [0.998923  , 1.        , 1.        ],
       [0.9956942 , 1.        , 1.        ],
       [0.9903207 , 0.99999994, 1.        ],
       [0.98281395, 0.99999994, 1.        ],
       [0.97319025, 0.9999999 , 1.        ],
       [0.9614702 , 0.9999998 , 1.        ],
       [0.9476791 , 0.99999976, 1.        ],
       [0.9318466 , 0.9999997 , 1.        ],
       [0.91400695, 0.9999996 , 1.        ]], dtype=float32)

In [68]:
f=np.stack([sin_values,cos_values],axis=2)
f

array([[[ 0.        ,  1.        ],
        [ 0.        ,  1.        ],
        [ 0.        ,  1.        ]],

       [[ 0.841471  ,  0.998923  ],
        [ 0.00215443,  1.        ],
        [ 0.00000464,  1.        ]],

       [[ 0.9092974 ,  0.9956942 ],
        [ 0.00430886,  1.        ],
        [ 0.00000928,  1.        ]],

       [[ 0.14112   ,  0.9903207 ],
        [ 0.00646326,  0.99999994],
        [ 0.00001392,  1.        ]],

       [[-0.7568025 ,  0.98281395],
        [ 0.00861763,  0.99999994],
        [ 0.00001857,  1.        ]],

       [[-0.9589243 ,  0.97319025],
        [ 0.01077196,  0.9999999 ],
        [ 0.00002321,  1.        ]],

       [[-0.2794155 ,  0.9614702 ],
        [ 0.01292625,  0.9999998 ],
        [ 0.00002785,  1.        ]],

       [[ 0.6569866 ,  0.9476791 ],
        [ 0.01508047,  0.99999976],
        [ 0.00003249,  1.        ]],

       [[ 0.98935825,  0.9318466 ],
        [ 0.01723462,  0.9999997 ],
        [ 0.00003713,  1.        ]],

       [[ 

In [69]:
final=np.zeros((seq_len,d_model),dtype="float32")
final[:,0::2]=final[:,0::2]+sin_values
final[:,1::2]=final[:,1::2]+cos_values
final

array([[ 0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ],
       [ 0.841471  ,  0.998923  ,  0.00215443,  1.        ,  0.00000464,
         1.        ],
       [ 0.9092974 ,  0.9956942 ,  0.00430886,  1.        ,  0.00000928,
         1.        ],
       [ 0.14112   ,  0.9903207 ,  0.00646326,  0.99999994,  0.00001392,
         1.        ],
       [-0.7568025 ,  0.98281395,  0.00861763,  0.99999994,  0.00001857,
         1.        ],
       [-0.9589243 ,  0.97319025,  0.01077196,  0.9999999 ,  0.00002321,
         1.        ],
       [-0.2794155 ,  0.9614702 ,  0.01292625,  0.9999998 ,  0.00002785,
         1.        ],
       [ 0.6569866 ,  0.9476791 ,  0.01508047,  0.99999976,  0.00003249,
         1.        ],
       [ 0.98935825,  0.9318466 ,  0.01723462,  0.9999997 ,  0.00003713,
         1.        ],
       [ 0.41211846,  0.91400695,  0.01938869,  0.9999996 ,  0.00004177,
         1.        ]], dtype=float32)

"NORMALIZATION"

In [70]:
from tensorflow.keras.layers import LayerNormalization

In [71]:
layer1=LayerNormalization(epsilon=1e-6)


In [72]:
final_out

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[-0.0199214 , -0.00875049,  0.00181175,  0.01826892,
          0.00781056,  0.02864456],
        [ 0.03406274,  0.0012218 ,  0.02320763,  0.02602022,
         -0.01496658,  0.00159727],
        [ 0.05205881,  0.00454618,  0.03034025,  0.02860425,
         -0.02255957, -0.00741928],
        [ 0.06105709,  0.00620842,  0.03390668,  0.02989632,
         -0.02635618, -0.01192771],
        [ 0.06645615,  0.00720578,  0.03604658,  0.03067158,
         -0.02863419, -0.01463281],
        [ 0.07005555,  0.00787069,  0.03747319,  0.03118843,
         -0.03015288, -0.01643623],
        [ 0.07262658,  0.00834564,  0.03849222,  0.0315576 ,
         -0.03123766, -0.0177244 ],
        [ 0.07455485,  0.00870185,  0.03925649,  0.03183449,
         -0.03205125, -0.01869053],
        [ 0.07605462,  0.0089789 ,  0.03985092,  0.03204984,
         -0.03268404, -0.01944197],
        [ 0.07725444,  0.00920054,  0.04032647,  0.03222213,
         -0.03

In [73]:
b

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[ 0.01501756, -0.01634905, -0.02886399,  0.01505661,
         -0.00933175,  0.02493191],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01759441,  0.02602669],
        [-0.00968037,  0.02821821,  0.04976651, -0.0002212 ,
          0.01

In [74]:
u=b+final_out
u

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[-0.00490385, -0.02509955, -0.02705224,  0.03332553,
         -0.00152119,  0.05357647],
        [ 0.02438237,  0.02944001,  0.07297413,  0.02579901,
          0.00262782,  0.02762396],
        [ 0.04237844,  0.03276439,  0.08010675,  0.02838305,
         -0.00496517,  0.01860741],
        [ 0.05137672,  0.03442663,  0.08367319,  0.02967512,
         -0.00876178,  0.01409898],
        [ 0.05677579,  0.03542399,  0.08581309,  0.03045038,
         -0.01103978,  0.01139388],
        [ 0.06037518,  0.03608891,  0.0872397 ,  0.03096723,
         -0.01255847,  0.00959046],
        [ 0.06294621,  0.03656385,  0.08825873,  0.0313364 ,
         -0.01364325,  0.00830229],
        [ 0.06487448,  0.03692006,  0.08902299,  0.03161328,
         -0.01445684,  0.00733616],
        [ 0.06637425,  0.03719711,  0.08961743,  0.03182864,
         -0.01508963,  0.00658473],
        [ 0.06757408,  0.03741876,  0.09009297,  0.03200093,
         -0.01

In [75]:
layer1_out=layer1(u)
layer1_out

<tf.Tensor: shape=(1, 10, 6), dtype=float32, numpy=
array([[[-0.32563877, -1.0089325 , -1.0749991 ,  0.9677995 ,
         -0.2111913 ,  1.6529622 ],
        [-0.28956664, -0.04917252,  2.0200424 , -0.22223234,
         -1.3235793 , -0.13549113],
        [ 0.36870039, -0.00445402,  1.8330661 , -0.17450881,
         -1.4688679 , -0.55393517],
        [ 0.5979991 ,  0.01193392,  1.7146795 , -0.15235388,
         -1.4813452 , -0.6909133 ],
        [ 0.70919   ,  0.02004647,  1.6463885 , -0.14048022,
         -1.4796028 , -0.7555413 ],
        [ 0.77413297,  0.02483869,  1.6029724 , -0.13317835,
         -1.4760582 , -0.7927067 ],
        [ 0.8165542 ,  0.02799118,  1.5731401 , -0.12825626,
         -1.4726882 , -0.8167407 ],
        [ 0.84638834,  0.03021932,  1.5514386 , -0.1247195 ,
         -1.4698021 , -0.8335246 ],
        [ 0.8684951 ,  0.03187633,  1.534965  , -0.12205809,
         -1.4673822 , -0.8458964 ],
        [ 0.8855245 ,  0.03315639,  1.522042  , -0.11998361,
         -1.46

In [22]:

def positional_encoding(seq_len,d_model):
    even_i=np.arange(0,d_model,2,dtype="float32")
    odd_i=np.arange(1,d_model,2,dtype="float32")
    pos=np.arange(0,seq_len,dtype="float32")
    pos=np.reshape(pos,(seq_len,1))
    sin=np.sin(pos/10000**(even_i/d_model))
    cos=np.cos(pos/10000**(even_i/d_model))
    final=np.zeros((seq_len,d_model),dtype="float32")
    final[:,0::2]=final[:,0::2]+sin
    final[:,1::2]=final[:,1::2]+cos
    return final
        

In [23]:
seq_len=10
d_model=6
p=positional_encoding(seq_len,d_model)
p

array([[ 0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ],
       [ 0.841471  ,  0.5403023 ,  0.04639922,  0.998923  ,  0.00215443,
         0.9999977 ],
       [ 0.9092974 , -0.4161468 ,  0.09269849,  0.9956942 ,  0.00430886,
         0.9999907 ],
       [ 0.14112   , -0.9899925 ,  0.13879807,  0.9903207 ,  0.00646326,
         0.99997914],
       [-0.7568025 , -0.6536436 ,  0.18459871,  0.98281395,  0.00861763,
         0.99996287],
       [-0.9589243 ,  0.28366217,  0.23000169,  0.97319025,  0.01077196,
         0.999942  ],
       [-0.2794155 ,  0.96017027,  0.27490923,  0.9614702 ,  0.01292625,
         0.99991643],
       [ 0.6569866 ,  0.75390226,  0.31922463,  0.9476791 ,  0.01508047,
         0.9998863 ],
       [ 0.98935825, -0.14550003,  0.36285236,  0.9318466 ,  0.01723462,
         0.99985147],
       [ 0.41211846, -0.91113025,  0.4056985 ,  0.91400695,  0.01938869,
         0.999812  ]], dtype=float32)

In [24]:
positional=np.repeat(p[np.newaxis,:,:],1000,axis=0)
positional

array([[[ 0.        ,  1.        ,  0.        ,  1.        ,
          0.        ,  1.        ],
        [ 0.841471  ,  0.5403023 ,  0.04639922,  0.998923  ,
          0.00215443,  0.9999977 ],
        [ 0.9092974 , -0.4161468 ,  0.09269849,  0.9956942 ,
          0.00430886,  0.9999907 ],
        ...,
        [ 0.6569866 ,  0.75390226,  0.31922463,  0.9476791 ,
          0.01508047,  0.9998863 ],
        [ 0.98935825, -0.14550003,  0.36285236,  0.9318466 ,
          0.01723462,  0.99985147],
        [ 0.41211846, -0.91113025,  0.4056985 ,  0.91400695,
          0.01938869,  0.999812  ]],

       [[ 0.        ,  1.        ,  0.        ,  1.        ,
          0.        ,  1.        ],
        [ 0.841471  ,  0.5403023 ,  0.04639922,  0.998923  ,
          0.00215443,  0.9999977 ],
        [ 0.9092974 , -0.4161468 ,  0.09269849,  0.9956942 ,
          0.00430886,  0.9999907 ],
        ...,
        [ 0.6569866 ,  0.75390226,  0.31922463,  0.9476791 ,
          0.01508047,  0.9998863 ],
  

In [25]:
embedded_tokens

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[ 0.0174959 , -0.04856312,  0.01922138,  0.00102691,
          0.03519565, -0.02182031],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        ...,
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706]],

       [[-0.02048524, -0.0469896 ,  0.02081491,  0.00982706,
         -0.03596616, -0.00721619],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        [ 0.02783685,  0.04820302,  0.0239727 ,  0.03132257,
         -0.02095261, -0.02396706],
        ...,
        [ 0.02783685,  0.04820302,  0.023972

In [26]:
embedded_tokens_with_position=embedded_tokens+positional
embedded_tokens_with_position

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[ 0.0174959 ,  0.9514369 ,  0.01922138,  1.0010269 ,
          0.03519565,  0.9781797 ],
        [ 0.8693079 ,  0.58850527,  0.07037193,  1.0302455 ,
         -0.01879817,  0.9760306 ],
        [ 0.93713427, -0.3679438 ,  0.11667119,  1.0270168 ,
         -0.01664375,  0.9760236 ],
        ...,
        [ 0.68482345,  0.80210525,  0.34319732,  0.9790017 ,
         -0.00587214,  0.9759192 ],
        [ 1.0171951 , -0.09729701,  0.38682505,  0.9631692 ,
         -0.00371799,  0.9758844 ],
        [ 0.43995532, -0.86292726,  0.4296712 ,  0.94532955,
         -0.00156391,  0.9758449 ]],

       [[-0.02048524,  0.9530104 ,  0.02081491,  1.009827  ,
         -0.03596616,  0.9927838 ],
        [ 0.8693079 ,  0.58850527,  0.07037193,  1.0302455 ,
         -0.01879817,  0.9760306 ],
        [ 0.93713427, -0.3679438 ,  0.11667119,  1.0270168 ,
         -0.01664375,  0.9760236 ],
        ...,
        [ 0.68482345,  0.80210525,  0.343197

In [124]:
embedded_tokens_with_position-positional

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[ 0.03189592,  0.04284692,  0.02828361, -0.00019079,
          0.01052318, -0.01416671],
        [ 0.01954019,  0.04382449, -0.01185715,  0.02980471,
          0.03980402, -0.00513357],
        [ 0.01954019,  0.04382449, -0.01185715,  0.02980471,
          0.03980402, -0.00513357],
        ...,
        [ 0.01954019,  0.04382443, -0.01185715,  0.02980471,
          0.03980402, -0.00513357],
        [ 0.01954025,  0.04382443, -0.01185715,  0.02980465,
          0.03980402, -0.00513357],
        [ 0.01954022,  0.04382443, -0.01185715,  0.02980465,
          0.03980402, -0.00513357]],

       [[-0.04189218,  0.03906476,  0.00642412,  0.022205  ,
          0.03240651,  0.02254772],
        [ 0.01954019,  0.04382449, -0.01185715,  0.02980471,
          0.03980402, -0.00513357],
        [ 0.01954019,  0.04382449, -0.01185715,  0.02980471,
          0.03980402, -0.00513357],
        ...,
        [ 0.01954019,  0.04382443, -0.011857

In [27]:
class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self,d_model:int,num_heads:int) -> None :
        super().__init__()
        self.d_model=d_model
        self.num_heads=num_heads
        self.wq=Dense(d_model)
        self.wk=Dense(d_model)
        self.wv=Dense(d_model)
        self.dense=Dense(d_model)
        self.d_head=d_model//num_heads
    def scaled_dot_product_attention(self,q,k,v):
        a=tf.matmul(q,k,transpose_b=True)
        dk = tf.cast(tf.shape(k)[-1], tf.float32)
        attention_weights=a/tf.math.sqrt(dk)
        #if mask is not None:
         #   attention_weights *=mask
        attention_scores=tf.nn.softmax(attention_weights)
        outputs=tf.matmul(attention_scores,v)
        return outputs,attention_scores
    def split_heads(self, x, batch_size,seq_len):
        x = tf.reshape(x, (batch_size,seq_len, self.num_heads, self.d_head))
        return tf.transpose(x, perm=[0, 2, 1, 3])
    def call(self,q,k,v):
        batch_size=tf.shape(q)[0]
        seq_len=tf.shape(q)[1]
        
        q=self.wq(q)
        k=self.wk(k)
        v=self.wv(v)
        q=self.split_heads(q,batch_size,seq_len)
        k=self.split_heads(k,batch_size,seq_len)
        v=self.split_heads(v,batch_size,seq_len)
        outputs,attention_weights=self.scaled_dot_product_attention(q,k,v)
        attention = tf.transpose(outputs, perm=[0, 2, 1, 3])
        attention = tf.reshape(attention, (batch_size, -1, self.d_model))
        output = self.dense(attention)
        return output

# Instantiate the MultiHeadAttention layer
d_model =d_model  # Example value for the model dimension
num_heads =2 # Example number of attention heads
mha_layer = MultiHeadAttention(d_model, num_heads)

# Example input tensors (replace with your actual data)
q = embedded_tokens_with_position  # Query tensor
k = embedded_tokens_with_position  # Key tensor
v = embedded_tokens_with_position  # Value tensor
mask = None  # Example mask (can be None or a proper mask tensor)

# Call the layer
output = mha_layer(q,k,v)

# Now `output` will be the result of the multi-head attention operation


In [102]:
embedded_tokens.shape

TensorShape([1000, 10, 6])

In [126]:
output

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[-0.00397599, -1.7318112 ,  0.9640919 , -0.4057583 ,
          0.46875125,  0.4576568 ],
        [-0.01607436, -1.7318373 ,  0.95567393, -0.39662755,
          0.46960425,  0.44119287],
        [-0.01649749, -1.7318355 ,  0.9553757 , -0.39630783,
          0.46963632,  0.44061774],
        ...,
        [-0.01182735, -1.731416  ,  0.9598668 , -0.39940628,
          0.46769238,  0.4464482 ],
        [-0.01444966, -1.7313972 ,  0.9580703 , -0.39741087,
          0.46782994,  0.4428633 ],
        [-0.00811082, -1.7310994 ,  0.96340203, -0.4018874 ,
          0.4661997 ,  0.45110637]],

       [[-0.00852537, -1.7333772 ,  0.9628786 , -0.4006862 ,
          0.46995687,  0.45308596],
        [-0.02069324, -1.7338722 ,  0.9529322 , -0.3919978 ,
          0.47273785,  0.4371584 ],
        [-0.02111137, -1.7338694 ,  0.95263726, -0.39168134,
          0.47276938,  0.43659014],
        ...,
        [-0.01644915, -1.7334487 ,  0.957124

"FEED FORWARD NETWORK"

In [28]:
class Feedforward(tf.keras.layers.Layer):
    def __init__(self,d_model,dff):
        super().__init__()
        self.d_model=d_model
        self.dff=dff
        self.layer1=tf.keras.layers.Dense(dff,activation="relu")
        self.layer2=tf.keras.layers.Dense(d_model)
    def call(self,x):
        out1=self.layer1(x)
        out2=self.layer2(out1)
        return out2
        
        


In [29]:
z=Feedforward(6,12)
g=z(output)
g

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[-0.61022586, -0.49591392,  0.51060534, -0.04468474,
          0.41995037, -0.42882416],
        [-0.6205668 , -0.49324903,  0.52078485, -0.06461248,
          0.43512237, -0.44964874],
        [-0.64271975, -0.5004587 ,  0.5326216 , -0.07277876,
          0.4471301 , -0.4792061 ],
        ...,
        [-0.6064602 , -0.48458388,  0.5034325 , -0.05406666,
          0.41820514, -0.432261  ],
        [-0.627763  , -0.4908124 ,  0.51899433, -0.065525  ,
          0.43349785, -0.46315965],
        [-0.64530754, -0.5001999 ,  0.52078646, -0.06104091,
          0.4344793 , -0.47979087]],

       [[-0.61230606, -0.49629155,  0.5064617 , -0.04427081,
          0.41815525, -0.42656162],
        [-0.6220283 , -0.4925817 ,  0.5163059 , -0.06435364,
          0.43276083, -0.44768125],
        [-0.6442938 , -0.50030077,  0.5284722 , -0.0716224 ,
          0.44456044, -0.4770985 ],
        ...,
        [-0.60742515, -0.48401394,  0.499572

"THE ENCODER"

In [30]:
class Encoder_layer(tf.keras.layers.Layer):
    def __init__(self,seq_len,d_model,num_heads,dff):
        super().__init__()
        self.attention=MultiHeadAttention(d_model=d_model,num_heads=num_heads)
        self.norm_and_add1=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm_and_add2=tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.feed_forward=Feedforward(dff=dff,d_model=d_model)
    def call(self,q,k,v):
        input=q
        attention_out=self.attention(q,k,v)
        norm_and_add1_out=self.norm_and_add1(input+attention_out)
        feed_forward_out=self.feed_forward(norm_and_add1_out)
        norm_and_add2_out=self.norm_and_add2(norm_and_add1_out+feed_forward_out)
        return norm_and_add2_out

In [31]:
s=Encoder_layer(seq_len=10,d_model=6,num_heads=2,dff=12)
out=s(q,k,v)
out

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[-1.7674524 ,  0.8021001 , -0.50217736,  1.3523242 ,
          0.32699525, -0.21179011],
        [-1.0585363 ,  0.2509984 , -0.85148585,  1.9417613 ,
          0.23350629, -0.5162437 ],
        [-0.6516402 , -0.8530159 , -0.669354  ,  2.0293152 ,
          0.44052088, -0.29582596],
        ...,
        [-1.420425  ,  0.4688456 , -0.5714838 ,  1.791646  ,
          0.17386079, -0.4424435 ],
        [-0.6309067 , -0.83203065, -0.55156964,  2.0861273 ,
          0.3184205 , -0.39004058],
        [-1.1519363 , -0.9817838 , -0.2589629 ,  1.8185704 ,
          0.5786714 , -0.00455871]],

       [[-1.7866192 ,  0.81561816, -0.4663725 ,  1.3483213 ,
          0.2718109 , -0.18275861],
        [-1.0557119 ,  0.25058958, -0.8541739 ,  1.9423537 ,
          0.23281172, -0.5158694 ],
        [-0.64807606, -0.85465693, -0.6714524 ,  2.0294032 ,
          0.43964323, -0.2948611 ],
        ...,
        [-1.4189428 ,  0.46843484, -0.573948

In [56]:
class Encoder(tf.keras.layers.Layer):
    def __init__(self,seq_len,d_model,num_heads,dff,num_encoders):
        super().__init__()
        self.num_encoders=num_encoders
        self.layer=[Encoder_layer(seq_len,d_model,num_heads,dff) for _ in range(self.num_encoders)]
    def call(self,q,k,v):
        x=q
        for i in range(self.num_encoders):
            x = self.layer[i](x,k,v)
        return x
    

In [57]:
o=Encoder(seq_len=10,d_model=6,num_heads=2,dff=12,num_encoders=12)
d=o(q,k,v)
d

<tf.Tensor: shape=(1000, 10, 6), dtype=float32, numpy=
array([[[ 0.50628793, -0.94086444, -1.5663532 ,  0.14671311,
          0.35074276,  1.5034741 ],
        [ 0.38438672, -1.4691136 , -1.0006918 , -0.19629021,
          0.98126745,  1.3004414 ],
        [-0.08471043, -1.2295943 , -0.9819014 , -0.04914698,
          1.7907505 ,  0.5546027 ],
        ...,
        [ 0.2770215 , -1.4702659 , -1.02554   , -0.07199535,
          0.9443675 ,  1.3464124 ],
        [-0.02061532, -1.1966019 , -1.0088803 , -0.13034385,
          1.7932318 ,  0.5632093 ],
        [-0.31471494, -1.202835  , -0.94413966,  0.06924944,
          1.7861594 ,  0.6062807 ]],

       [[ 0.5099705 , -0.90431035, -1.5713065 ,  0.12610371,
          0.3093272 ,  1.5302154 ],
        [ 0.36907357, -1.4866562 , -0.9850445 , -0.17855337,
          0.9831939 ,  1.2979866 ],
        [-0.07915566, -1.2379464 , -0.97649366, -0.04759281,
          1.7889923 ,  0.55219615],
        ...,
        [ 0.2736194 , -1.4797823 , -1.012270